const fs = require('fs');
const path = require('path');

const data = {
  id: "veterinary",
  name: "수의학",
  subcategories: [
    {
      id: "vet-nutrition",
      name: "영양학",
      icon: "🥗",
      topics: [
        { title: "6대 필수 영양소의 역할과 균형", description: "단백질, 지방, 탄수화물, 비타민, 미네랄, 수분의 기능과 적정 비율.", tags: ["기초영양","필수영양소"], animal: "both", difficulty: "basic", viralScore: 65 },
        { title: "단백질 품질이 반려동물에 미치는 영향", description: "육류 단백질과 식물성 단백질의 차이점 및 아미노산 프로파일 이해하기.", tags: ["단백질","아미노산"], animal: "both", difficulty: "intermediate", viralScore: 70 },
        { title: "필수 지방산 오메가-3와 오메가-6의 완벽한 균형", description: "피부, 모질, 관절 건강을 위한 필수 지방산의 황금 비율 맞추기.", tags: ["지방산","오메가3"], animal: "both", difficulty: "intermediate", viralScore: 75 },
        { title: "반려동물 사료 속 탄수화물, 꼭 필요할까?", description: "탄수화물 급여 찬반 논쟁과 적절한 섭취량이 건강에 미치는 영향.", tags: ["탄수화물","사료논쟁"], animal: "both", difficulty: "advanced", viralScore: 88 },
        { title: "비타민 A, D 중독의 위험성과 예방법", description: "지용성 비타민의 과다 섭취가 부르는 심각한 중독 증상과 적정량.", tags: ["비타민독성","영양학"], animal: "both", difficulty: "advanced", viralScore: 80 },
        { title: "칼슘과 인의 미네랄 비율이 뼈 건강에 미치는 영향", description: "특히 성장기 강아지와 고양이에게 중요한 칼슘과 인의 정확한 비율 맞추기.", tags: ["미네랄","칼슘"], animal: "both", difficulty: "intermediate", viralScore: 72 },
        { title: "반려동물 수분 부족이 부르는 치명적인 질환", description: "만성 탈수가 신장과 요로계에 미치는 악영향과 수분 섭취 늘리는 꿀팁.", tags: ["수분섭취","음수량"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "고양이에게 타우린이 절대적으로 필요한 이유", description: "타우린 결핍 시 발생하는 심장 질환(DCM)과 실명 등 치명적인 부작용.", tags: ["타우린","고양이영양"], animal: "cat", difficulty: "basic", viralScore: 85 },
        { title: "강아지 고양이 유산균, 프로바이오틱스의 진짜 효과", description: "장 건강부터 면역력 강화까지, 프로바이오틱스와 프리바이오틱스 선택법.", tags: ["프로바이오틱스","장건강"], animal: "both", difficulty: "intermediate", viralScore: 82 },
        { title: "생식(BARF) 급여, 기적의 식단일까 위험한 선택일까?", description: "생식의 장점과 살모넬라균 등 감염 위험성에 대한 심층 분석.", tags: ["생식","BARF"], animal: "both", difficulty: "advanced", viralScore: 95 },
        { title: "완벽한 육식동물 고양이의 특수한 단백질 대사", description: "고양이가 왜 강아지보다 더 많은 단백질을 요구하는지에 대한 과학적 이유.", tags: ["고양이영양","단백질"], animal: "cat", difficulty: "advanced", viralScore: 78 },
        { title: "노령견 노령묘를 위한 맞춤형 영양 관리법", description: "노화에 따른 소화력 저하와 질환 예방을 위한 시니어 식단 가이드.", tags: ["노령동물","시니어사료"], animal: "both", difficulty: "intermediate", viralScore: 85 },
        { title: "폭풍 성장기 퍼피와 키튼을 위한 필수 영양 가이드", description: "골격 발달과 면역력을 위한 성장기 1년간의 핵심 영양소 섭취 방법.", tags: ["성장기","퍼피사료"], animal: "both", difficulty: "intermediate", viralScore: 77 },
        { title: "임신과 수유기 모견/모묘를 위한 특별 영양 처방", description: "에너지 요구량이 급증하는 임신 및 수유 기간의 안전하고 충분한 영양 공급.", tags: ["임신수유","영양관리"], animal: "both", difficulty: "advanced", viralScore: 70 },
        { title: "우리 아이 비만도 평가, BCS(신체충실지수) 측정법", description: "집에서 쉽게 따라 할 수 있는 갈비뼈와 허리 라인을 통한 객관적인 비만도 체크.", tags: ["비만도","BCS"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "실패 없는 건강한 반려동물 다이어트 플랜", description: "요요 현상 없이 안전하게 체중을 감량하는 식단 조절과 칼로리 계산법.", tags: ["다이어트","비만관리"], animal: "both", difficulty: "intermediate", viralScore: 92 },
        { title: "식이섬유, 변비 해결부터 혈당 조절까지의 효능", description: "수용성 및 불용성 식이섬유가 장 건강과 다이어트에 미치는 놀라운 효과.", tags: ["식이섬유","장건강"], animal: "both", difficulty: "intermediate", viralScore: 75 },
        { title: "항산화제가 노화 예방과 인지 기능에 미치는 영향", description: "비타민 E, C 등 항산화 영양소가 뇌 건강과 세포 노화를 늦추는 원리.", tags: ["항산화","노화방지"], animal: "both", difficulty: "advanced", viralScore: 81 },
        { title: "EPA와 DHA, 뇌 발달과 관절 염증 감소의 핵심", description: "오메가-3의 핵심 성분인 EPA와 DHA가 심장, 뇌, 관절 건강을 지키는 이유.", tags: ["EPA","DHA"], animal: "both", difficulty: "intermediate", viralScore: 83 },
        { title: "위험한 영양제 조합, 영양소 상호작용의 비밀", description: "특정 미네랄이나 비타민을 함께 먹였을 때 흡수율이 떨어지거나 부작용이 생기는 경우.", tags: ["영양제","상호작용"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "수제 사료 만들기, 영양 불균형의 위험성", description: "집에서 직접 사료를 만들 때 흔히 놓치는 필수 영양소 결핍 문제점.", tags: ["수제사료","영양불균형"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "하루 적정 간식량 10% 법칙, 왜 중요할까?", description: "사료 외 간식 섭취가 하루 권장 칼로리의 10%를 넘지 않아야 하는 이유.", tags: ["간식","칼로리제한"], animal: "both", difficulty: "basic", viralScore: 86 },
        { title: "미래 식량 곤충 단백질, 알레르기 예방 효과는?", description: "환경 보호는 물론 식이 알레르기 해결책으로 떠오르는 동애등에 등 곤충 사료.", tags: ["곤충단백질","저알레르기"], animal: "both", difficulty: "intermediate", viralScore: 79 },
        { title: "발효 사료가 소화 흡수율과 장내 환경에 미치는 영향", description: "유익균을 활용한 발효 과정을 거친 사료의 소화율 개선 및 면역력 강화 효과.", tags: ["발효사료","소화율"], animal: "both", difficulty: "advanced", viralScore: 72 },
        { title: "반려동물 채식(비건) 사료, 과연 건강할까?", description: "강아지와 고양이에게 식물성 단백질만으로 필수 아미노산을 채울 수 있는지에 대한 논쟁.", tags: ["채식사료","비건사료"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "동결건조 사료의 영양학적 장점과 급여 주의사항", description: "원물의 영양소를 보존하는 동결건조 공법의 특징과 반드시 물에 불려 급여해야 하는 이유.", tags: ["동결건조","프리미엄사료"], animal: "both", difficulty: "intermediate", viralScore: 84 },
        { title: "사료 산패를 막는 올바른 보관법과 용기 선택", description: "빛, 열, 습기로 인한 사료 변질과 독성 곰팡이 생성을 막는 과학적인 보관 가이드.", tags: ["사료보관","산패방지"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "효과적인 관절 영양제 성분(글루코사민, 콘드로이친) 분석", description: "슬개골 탈구와 관절염 예방에 도움을 주는 영양 성분의 실제 효능과 한계.", tags: ["관절영양제","글루코사민"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "NRC, AAFCO, FEDIAF 영양 기준의 이해", description: "반려동물 사료 포장지에 적힌 영양 기준 협회들의 차이점과 최소 충족 요건.", tags: ["AAFCO","사료기준"], animal: "both", difficulty: "advanced", viralScore: 76 },
        { title: "반려동물 하루 권장 음수량 계산과 수분 보충 전략", description: "체중 1kg당 필요한 정확한 음수량 공식과 자발적인 물 섭취를 유도하는 환경 조성법.", tags: ["음수량계산","수분보충"], animal: "both", difficulty: "basic", viralScore: 93 }
      ]
    },
    {
      id: "vet-petfood",
      name: "사료학",
      icon: "🍖",
      topics: [
        { title: "사료 성분표의 눈속임, '원료 쪼개기'의 진실", description: "주원료 순서를 바꾸기 위해 탄수화물 원료를 여러 개로 나누어 표기하는 꼼수 파악하기.", tags: ["원료쪼개기","라벨읽기"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "사료 라벨 완벽하게 읽는 법 기초 가이드", description: "사용 원료 명칭, 등록성분량, 유통기한 등 사료 뒷면 라벨을 정확하게 해석하는 방법.", tags: ["라벨읽기","사료선택"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "육류 부산물(Meat By-products), 먹여도 안전한가?", description: "근육육 외의 내장, 뼈 등 부산물이 영양학적으로 나쁜 것인지에 대한 진실과 오해.", tags: ["부산물","사료성분"], animal: "both", difficulty: "intermediate", viralScore: 91 },
        { title: "홀리스틱, 휴먼그레이드 사료 등급의 마케팅 함정", description: "법적 기준이 없는 사료 등급(프리미엄, 슈퍼프리미엄 등) 마케팅 용어의 실체 파악.", tags: ["사료등급","마케팅"], animal: "both", difficulty: "intermediate", viralScore: 95 },
        { title: "건식 사료 vs 습식 사료, 우리 아이에게 맞는 것은?", description: "수분 함량, 치아 건강, 기호성을 고려한 건사료와 캔/파우치 사료의 장단점 비교.", tags: ["건식습식","사료비교"], animal: "both", difficulty: "basic", viralScore: 85 },
        { title: "그레인프리 사료와 심장병(DCM) 연관성 논란", description: "곡물 대신 콩류와 감자를 넣은 그레인프리 식단이 확장성 심근병증을 유발한다는 FDA 조사 결과.", tags: ["그레인프리","DCM"], animal: "dog", difficulty: "advanced", viralScore: 98 },
        { title: "우리 아이 사료 리콜 확인하는 방법 (국내외)", description: "살모넬라균 감염, 독소 검출 등으로 인한 해외 및 국내 사료 리콜 내역 조회 방법.", tags: ["사료리콜","안전성"], animal: "both", difficulty: "intermediate", viralScore: 82 },
        { title: "설사 없이 안전한 사료 전환 방법 (7일의 법칙)", description: "기존 사료에서 새로운 사료로 바꿀 때 위장관 트러블을 예방하는 점진적 비율 조절법.", tags: ["사료전환","장건강"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "칼로리 계산과 체중 감량을 위한 사료 급여량 조절", description: "휴식기 에너지 요구량(RER)과 유지 에너지 요구량(MER)을 활용한 정확한 급여량 계산.", tags: ["칼로리계산","급여량"], animal: "both", difficulty: "advanced", viralScore: 86 },
        { title: "단일 단백질 LID 사료의 진정한 알레르기 진단 효과", description: "Limited Ingredient Diet가 식이 알레르기를 감별하고 관리하는 데 도움을 주는 원리.", tags: ["LID사료","알레르기"], animal: "both", difficulty: "intermediate", viralScore: 80 },
        { title: "비싼 프리미엄 사료, 가격만큼 가치가 있을까?", description: "고가 사료의 원료 품질과 공정 차이가 실제로 반려동물 건강 수명에 미치는 영향 분석.", tags: ["프리미엄사료","가성비"], animal: "both", difficulty: "intermediate", viralScore: 92 },
        { title: "실제 개와 고양이 대상 '급여 시험'을 통과한 사료의 의미", description: "단순 성분 분석을 넘어 장기간 급여 테스트를 통해 영양 적합성을 검증받은 사료 선택법.", tags: ["급여시험","AAFCO"], animal: "both", difficulty: "advanced", viralScore: 78 },
        { title: "유기농 사료 인증 마크의 기준과 신뢰성", description: "USDA 오가닉 등 공신력 있는 유기농 인증 마크를 획득하기 위한 조건과 실제 안전성.", tags: ["유기농사료","인증마크"], animal: "both", difficulty: "intermediate", viralScore: 75 },
        { title: "사료 포장지의 화려한 문구에 숨겨진 마케팅 트릭", description: "천연, 신선한, 야생의 등 소비자를 현혹하는 단어들이 실제 성분과 어떻게 다른지 해부.", tags: ["사료마케팅","과대광고"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "처방식 사료 가격이 유독 비싼 합리적인 이유", description: "일반 사료와 달리 연구 개발비, 임상 실험, 특수 공정이 들어가는 처방식의 원가 구조.", tags: ["처방식","사료가격"], animal: "both", difficulty: "advanced", viralScore: 81 },
        { title: "국내외 사료 제조 관리법 및 규제 차이", description: "미국 FDA, 유럽 FEDIAF와 한국의 사료 관리법이 요구하는 품질 및 위생 기준 비교.", tags: ["사료규제","제조법"], animal: "both", difficulty: "advanced", viralScore: 68 },
        { title: "합성 보존료(BHA, BHT) vs 천연 보존료(토코페롤)", description: "사료 산패를 막기 위해 첨가되는 인공 방부제의 유해성 논란과 비타민 E 등 천연 항산화제의 한계.", tags: ["보존료","방부제"], animal: "both", difficulty: "advanced", viralScore: 87 },
        { title: "미트밀(육분) vs 신선육(생육)의 영양학적 차이", description: "렌더링 과정을 거친 육분과 신선한 고기가 수분 함량 및 단백질 흡수율에 미치는 차이.", tags: ["미트밀","신선육"], animal: "both", difficulty: "intermediate", viralScore: 84 },
        { title: "연령별(퍼피-어덜트-시니어) 사료 전환의 최적 타이밍", description: "소형견, 대형견, 고양이의 성장 속도에 맞춘 생애 주기별 사료 교체 시기 가이드.", tags: ["연령별사료","생애주기"], animal: "both", difficulty: "basic", viralScore: 86 },
        { title: "다견 다묘 가정을 위한 멀티펫 급여 전략", description: "서로 다른 사료를 먹어야 하는 반려동물들의 밥그릇 다툼과 식단 혼합을 막는 노하우.", tags: ["다견가정","자율급식"], animal: "both", difficulty: "basic", viralScore: 83 },
        { title: "식이 알레르기와 음식 불내증의 차이와 구별법", description: "면역 반응이 개입하는 알레르기와 단순 소화 불량인 불내증을 구별하고 알맞은 사료 찾기.", tags: ["알레르기","불내증"], animal: "both", difficulty: "advanced", viralScore: 89 },
        { title: "영양 만점 토퍼(Topper) 올바르게 사용하는 방법", description: "기호성을 높이기 위해 사료 위에 뿌려주는 토퍼가 전체 칼로리와 영양 균형을 깨지 않도록 급여하기.", tags: ["사료토퍼","기호성"], animal: "both", difficulty: "intermediate", viralScore: 81 },
        { title: "고양이 사료에 반드시 포함되어야 할 필수 성분 4가지", description: "아라키돈산, 타우린, 비타민 A, 나이아신 등 강아지와 달리 스스로 합성하지 못하는 고양이 필수 영양소.", tags: ["고양이사료","필수영양"], animal: "cat", difficulty: "advanced", viralScore: 85 },
        { title: "우리 아이에게 딱 맞는 정확한 사료 급여량 계산 공식", description: "사료 포장지의 권장량에 의존하지 않고 체중, 활동량, 중성화 여부에 따른 1일 요구 대사 에너지(DER) 계산법.", tags: ["급여량계산","DER"], animal: "both", difficulty: "advanced", viralScore: 88 },
        { title: "사람이 먹는 식재료로 만든 '프레시 푸드' 화식의 명암", description: "최근 유행하는 냉장 배송 화식 사료의 높은 소화흡수율 장점과 짧은 유통기한 및 보관의 어려움.", tags: ["화식","프레시푸드"], animal: "both", difficulty: "intermediate", viralScore: 82 },
        { title: "사료 라벨의 '보장 분석치' 완벽 해독 가이드", description: "조단백, 조지방, 수분, 조회분 등 보장 분석치가 의미하는 바와 건물 기준(Dry Matter Basis)으로 변환하여 비교하는 법.", tags: ["보장분석치","사료비교"], animal: "both", difficulty: "advanced", viralScore: 90 },
        { title: "사료 성분표에 적힌 미지의 화학물질 'E 번호'의 정체", description: "착색료, 향미제, 보존제 등으로 사용되는 E 넘버 식품 첨가물의 안전성과 유의미한 부작용.", tags: ["식품첨가물","E번호"], animal: "both", difficulty: "advanced", viralScore: 79 },
        { title: "믿고 먹일 수 있는 사료 공장의 위생 및 품질 관리 기준", description: "ISO 9001, HACCP 등 안전한 반려동물 식품 제조 공정이 갖춰야 할 필수 인증과 품질 관리 시스템.", tags: ["사료공장","품질관리"], animal: "both", difficulty: "intermediate", viralScore: 74 },
        { title: "사료 제조 과정에서 발생하는 '교차 오염'의 위험성", description: "하나의 생산 라인에서 여러 처방식과 일반 사료를 만들 때 발생할 수 있는 성분 혼입 및 알레르기 유발 위험.", tags: ["교차오염","제조공정"], animal: "both", difficulty: "advanced", viralScore: 84 },
        { title: "한국 반려인들이 선호하는 인기 사료 브랜드 트렌드 분석", description: "국내 사료 시장의 주요 인기 브랜드 특징과 수입 사료 의존도, 국산 사료의 품질 향상 추세.", tags: ["사료브랜드","트렌드"], animal: "both", difficulty: "basic", viralScore: 77 }
      ]
    },
    {
      id: "vet-disease",
      name: "질병백과",
      icon: "🏥",
      topics: [
        { title: "소형견 고질병 1위, 슬개골 탈구 원인과 예방수술", description: "포메라니안, 말티즈에서 흔한 무릎 관절 탈구 증상 1~4기 구분과 수술적, 비수술적 관리법.", tags: ["슬개골탈구","관절질환"], animal: "dog", difficulty: "intermediate", viralScore: 95 },
        { title: "고양이의 소리 없는 킬러, 만성 신장병(CKD) 관리", description: "다음다뇨와 체중 감소로 시작되는 고양이 신부전의 원인, SDMA 검사, 그리고 보호자의 장기 케어 방법.", tags: ["만성신장병","신부전"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "절대 먹이면 안 되는 반려동물 치명적 독성 식품 리스트", description: "초콜릿, 포도, 양파, 자일리톨 등 급성 신부전이나 적혈구 파괴를 일으키는 일상 속 위험 음식들.", tags: ["독성식품","금기음식"], animal: "both", difficulty: "basic", viralScore: 98 },
        { title: "모기 한 마리의 공포, 심장사상충 감염과 치료 과정", description: "예방약으로 100% 막을 수 있지만 감염 시 치명적인 폐동맥 및 심장 손상을 일으키는 심장사상충의 진단과 치료.", tags: ["심장사상충","기생충"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "밤새 긁는 강아지, 난치성 피부병 아토피성 피부염 정복기", description: "집먼지진드기, 꽃가루 등 환경 알레르겐에 대한 과민 반응과 가려움증을 완화하는 최신 치료 옵션.", tags: ["아토피","피부병"], animal: "dog", difficulty: "intermediate", viralScore: 91 },
        { title: "수컷 고양이의 응급 질환, 하부요로기계질환(FLUTD)과 요도폐색", description: "스트레스와 결석으로 요도가 막혀 오줌을 싸지 못하는 급성 신부전 유발 요로 질환의 증상과 카테터 처치.", tags: ["FLUTD","요도폐색"], animal: "cat", difficulty: "advanced", viralScore: 97 },
        { title: "반려동물 당뇨병, 인슐린 주사와 혈당 관리의 모든 것", description: "다음, 다뇨, 다식, 체중 감소의 4다(多) 증상을 보이는 당뇨병의 진단과 집에서의 인슐린 투여 및 식단 관리법.", tags: ["당뇨","내분비질환"], animal: "both", difficulty: "advanced", viralScore: 89 },
        { title: "기름진 음식의 저주, 급성 췌장염의 끔찍한 통증과 치료", description: "사람 음식을 먹은 후 심한 구토와 복통을 호소하는 췌장염의 원인, 염증 수치(cPL/fPL) 검사, 입원 수액 치료.", tags: ["췌장염","소화기질환"], animal: "both", difficulty: "intermediate", viralScore: 94 },
        { title: "강아지 갑상선 기능 저하증 vs 고양이 갑상선 기능 항진증", description: "살이 찌고 무기력해지는 개와 갈수록 마르고 공격적으로 변하는 고양이의 상반된 갑상선 질환 증상 비교.", tags: ["갑상선","호르몬질환"], animal: "both", difficulty: "advanced", viralScore: 88 },
        { title: "배가 불룩해지고 털이 빠지는 쿠싱 증후군(부신피질항진증)", description: "노령견에서 다발하는 코르티솔 호르몬 과다 분비 질환의 특징적인 증상(올챙이배, 다뇨)과 평생 약물 관리.", tags: ["쿠싱","내분비질환"], animal: "dog", difficulty: "advanced", viralScore: 90 },
        { title: "입냄새의 원인, 치주 질환이 전신 건강에 미치는 악영향", description: "치석으로 인한 치은염이 심장판막과 신장까지 세균 감염을 일으킬 수 있는 치주염의 위험성과 스케일링의 중요성.", tags: ["치주질환","치과"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "강아지와 고양이의 구토 vs 역류, 어떻게 구별할까?", description: "위 내용물이 나오는 능동적인 구토와 식도에서 소화되지 않은 음식이 나오는 수동적 역류의 차이점 및 원인 감별.", tags: ["구토","역류"], animal: "both", difficulty: "basic", viralScore: 85 },
        { title: "갑작스러운 발작과 경련, 특발성 뇌전증(간질) 대처법", description: "원인을 알 수 없는 신경 발작 증상 발생 시 보호자의 응급 대처 요령과 항경련제 약물 치료 프로토콜.", tags: ["뇌전증","신경질환"], animal: "both", difficulty: "advanced", viralScore: 92 },
        { title: "다리를 들고 걷는 강아지, 전십자인대 파열의 원인과 수술", description: "산책 중 갑작스러운 뒷다리 파행을 유발하는 무릎 인대 파열의 TPLO 등 외과적 수술 방법과 재활 치료.", tags: ["십자인대","정형외과"], animal: "dog", difficulty: "advanced", viralScore: 88 },
        { title: "고양이 돌연사의 원인, 비대성 심근병증(HCM)", description: "메인쿤, 랙돌에서 유전적으로 발생하며 심장 근육이 두꺼워져 혈전과 폐수종을 유발하는 치명적인 심장병.", tags: ["HCM","심장병"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "새끼 강아지의 생명을 위협하는 치명적인 장염, 파보 바이러스", description: "피 섞인 설사와 구토를 유발하며 치사율이 높은 파보 바이러스의 전염 경로, 백신 예방, 항체 치료법.", tags: ["파보","전염병"], animal: "dog", difficulty: "advanced", viralScore: 95 },
        { title: "불치병에서 치료 가능한 질병으로, 고양이 전염성 복막염(FIP)", description: "코로나 바이러스 변이로 발생하여 복수가 차거나 신경 증상을 보이는 FIP의 최신 항바이러스제 치료 성공 사례.", tags: ["FIP","전염병"], animal: "cat", difficulty: "advanced", viralScore: 98 },
        { title: "장난감, 머리끈 이물 섭취 시 내시경 vs 개복 수술", description: "반려동물이 삼킨 이물의 위치와 재질에 따른 구토 유발, 내시경 제거, 그리고 위/장 절개 수술의 결정 기준.", tags: ["이물섭취","응급수술"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "머리를 털고 귀에서 악취가 나는 외이염 완치 가이드", description: "말라세지아 세균 감염이나 알레르기로 인해 반복되는 만성 귀 염증의 올바른 세정법과 연고 도포 방법.", tags: ["외이염","귀청소"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "점액성 혈변과 젤리똥, 강아지 대장염의 원인과 치료", description: "스트레스, 식이 변화, 기생충 등으로 장 점막이 손상되어 나타나는 급만성 대장염의 증상과 유산균 처방.", tags: ["혈변","장염"], animal: "dog", difficulty: "intermediate", viralScore: 86 },
        { title: "반려동물 사망 원인 1위 종양, 악성 암과 양성 종양의 차이", description: "비만세포종, 림프종, 유선종양 등 노령 동물에게 흔한 암의 진단적 접근(FNA, 조직검사)과 항암 치료 및 예후 예측.", tags: ["종양","항암치료"], animal: "both", difficulty: "advanced", viralScore: 95 },
        { title: "눈동자가 하얗게 변하는 백내장과 핵경화증 구별하기", description: "노화로 인한 수정체 경화와 시력을 잃게 만드는 당뇨성/유전성 백내장의 차이점 및 인공수정체 삽입 수술.", tags: ["백내장","안과"], animal: "both", difficulty: "intermediate", viralScore: 90 },
        { title: "뒷다리 마비와 심한 통증, 강아지 디스크(IVDD) 질환", description: "닥스훈트, 웰시코기 등 연골발육부전 견종에서 다발하는 추간판 탈출증의 증상 단계, 침술 및 외과적 감압술.", tags: ["디스크","신경질환"], animal: "dog", difficulty: "advanced", viralScore: 92 },
        { title: "풀밭 산책의 불청객, 진드기 매개 질환(바베시아, 라임병)", description: "살인 진드기에 물려 적혈구가 파괴되는 바베시아증과 관절염을 유발하는 라임병의 치명적인 증상과 예방법.", tags: ["진드기","매개질환"], animal: "both", difficulty: "intermediate", viralScore: 94 },
        { title: "거위 소리 기침을 하는 전염성 기관지염, 켄넬코프", description: "애견카페나 유치원 등 밀집된 환경에서 바이러스 감염으로 발생하는 전염성 호흡기 질환의 치료와 백신.", tags: ["켄넬코프","호흡기질환"], animal: "dog", difficulty: "basic", viralScore: 84 },
        { title: "새끼 고양이의 장염, 생존율이 낮은 범백혈구감소증(범백)", description: "백혈구 수치가 급감하고 심한 구토와 설사를 동반하는 고양이 범백의 강한 전염성과 격리 입원 치료 과정.", tags: ["범백","전염병"], animal: "cat", difficulty: "advanced", viralScore: 97 },
        { title: "고양이 치아가 녹아내리는 흡수성 병변(FORL)의 엄청난 통증", description: "정확한 원인 없이 치아 뿌리부터 녹아 흡수되는 질환으로 사료를 흘리거나 씹지 못하는 고양이의 전체 발치 치료.", tags: ["FORL","치과"], animal: "cat", difficulty: "advanced", viralScore: 93 },
        { title: "호흡 곤란을 유발하는 소형견 기도의 붕괴, 기관허탈", description: "요크셔테리어, 포메라니안 등에서 기관지 연골이 약해져 숨이 막히고 켁켁거리는 증상의 내과적 관리와 스텐트 시술.", tags: ["기관허탈","호흡기질환"], animal: "dog", difficulty: "intermediate", viralScore: 91 },
        { title: "침을 흘리고 밥을 거부하는 난치성 고양이 만성 구내염", description: "면역 과잉 반응으로 구강 점막 전체에 궤양과 염증이 생기는 심각한 구내염의 스테로이드 치료와 전/부분 발치술.", tags: ["구내염","치과"], animal: "cat", difficulty: "advanced", viralScore: 94 },
        { title: "정확한 원인을 찾는 혈청 알레르기(IgE) 검사의 허와 실", description: "피부나 혈액을 통한 알레르기 항원 검사가 음식 알레르기를 진단하는 데 한계가 있으며 환경 알레르기에 더 적합한 이유.", tags: ["알레르기검사","아토피"], animal: "both", difficulty: "advanced", viralScore: 85 }
      ]
    },
    {
      id: "vet-prescription",
      name: "처방식/치료식",
      icon: "💊",
      topics: [
        { title: "신장 처방식(Renal Diet)이 생명을 연장하는 핵심 원리", description: "단백질과 인의 제한이 신장의 과부하를 줄이고 요독증을 예방하는 매커니즘.", tags: ["신장처방식","신부전"], animal: "both", difficulty: "advanced", viralScore: 92 },
        { title: "간 질환 처방식(Hepatic)의 단백질 조절과 구리 제한", description: "간성뇌증 예방을 위한 고품질 단백질 사용과 간에 축적되는 구리를 줄인 특별한 레시피.", tags: ["간질환","처방식"], animal: "both", difficulty: "advanced", viralScore: 85 },
        { title: "요로결석(스트루바이트, 칼슘옥살레이트) 맞춤형 비뇨기 처방식", description: "소변 pH를 조절하고 결석의 원인이 되는 미네랄을 제한하여 결석 용해 및 재발을 방지하는 c/d, s/o 사료.", tags: ["요로결석","비뇨기계"], animal: "both", difficulty: "intermediate", viralScore: 90 },
        { title: "만성 설사와 구토를 멈추는 위장관(Gastrointestinal) 처방식", description: "소화 흡수율을 극대화하고 유익한 식이섬유를 포함하여 장 점막 회복을 돕는 저지방 위장관 사료.", tags: ["위장관","소화기질환"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "당뇨병 관리를 위한 고단백 저탄수화물 처방식의 중요성", description: "식후 혈당 스파이크를 막기 위해 혈당 지수(GI)가 낮은 탄수화물과 복합 식이섬유를 배합한 당뇨 사료.", tags: ["당뇨","혈당관리"], animal: "both", difficulty: "advanced", viralScore: 87 },
        { title: "요요 없는 체중 감량을 위한 비만 관리(Satiety) 처방식", description: "포만감을 극대화하는 고식이섬유와 근손실을 막는 고단백으로 설계된 과학적인 다이어트 처방식.", tags: ["비만관리","다이어트"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "식이 알레르기 극복의 열쇠, 가수분해(Hypoallergenic) 처방식", description: "단백질 입자를 면역 세포가 인식하지 못할 정도로 잘게 쪼개어 알레르기 반응을 원천 차단하는 z/d, 아노알러제닉.", tags: ["가수분해","알레르기"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "관절염 통증을 완화하는 모빌리티(Mobility) 처방식의 효능", description: "고함량의 오메가-3(EPA)와 관절 연골 보호 성분을 포함하여 진통제 투여량을 줄여주는 관절 처방식.", tags: ["관절","관절염"], animal: "dog", difficulty: "intermediate", viralScore: 86 },
        { title: "심장병의 진행을 늦추는 저나트륨 심장 처방식(Cardiac)", description: "혈압 상승과 폐수종을 막기 위해 나트륨을 엄격히 제한하고 타우린과 L-카르니틴을 보강한 심장병 맞춤 식단.", tags: ["심장","심부전"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "피부 장벽을 강화하는 더마(Dermatology) 처방식", description: "아토피성 피부염의 염증을 가라앉히는 특수 필수 지방산 배합과 알로에, 강황 등 피부 진정 성분을 포함한 사료.", tags: ["피부","아토피"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "노령견 치매 예방과 뇌 기능 개선을 위한 인지기능 처방식", description: "MCT(중쇄중성지방)와 항산화 물질을 통해 노화된 뇌세포에 에너지를 공급하여 인지장애증후군(치매)을 개선하는 식단.", tags: ["인지기능","치매"], animal: "dog", difficulty: "advanced", viralScore: 85 },
        { title: "급성 췌장염 발병 후 필수인 초저지방(Low Fat) 처방식", description: "지방 소화 능력이 떨어진 췌장을 쉬게 하고 재발을 막기 위해 지방 함량을 극도로 낮춘 i/d low fat 사료.", tags: ["췌장염후","저지방"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "힐스, 로얄캐닌, 퓨리나 3대 처방식 브랜드 특징 비교", description: "전 세계 수의사들이 가장 많이 처방하는 메이저 처방식 브랜드들의 영양학적 접근 방식과 기호성 차이.", tags: ["브랜드비교","처방식"], animal: "both", difficulty: "intermediate", viralScore: 84 },
        { title: "수제 화식으로 처방식을 완벽하게 대체할 수 있을까?", description: "수의 영양학 전문의의 레시피 없이 임의로 만든 질환식 화식이 오히려 질병을 악화시킬 수 있는 치명적인 이유.", tags: ["수제대체","영양불균형"], animal: "both", difficulty: "advanced", viralScore: 95 },
        { title: "신장병과 췌장염이 동시에! 복합 질환 시 처방식 선택 기준", description: "단백질을 제한해야 하는 신장병과 지방을 제한해야 하는 췌장염 등 상충되는 질환을 가진 환자의 식단 설계 딜레마.", tags: ["복합질환","수의학"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "암 환자를 위한 항암 보조(Oncology) 처방식의 원리", description: "종양 세포의 에너지원인 탄수화물은 줄이고, 정상 세포의 염증을 줄이는 고함량 아미노산과 오메가3를 포함한 식단.", tags: ["항암","종양"], animal: "both", difficulty: "advanced", viralScore: 90 },
        { title: "고양이 갑상선 기능 항진증을 치료하는 요오드 제한(y/d) 사료", description: "갑상선 호르몬의 원료가 되는 요오드를 극도로 제한하여 약물 투여 없이 호르몬 수치를 정상화하는 처방식.", tags: ["갑상선","고양이처방식"], animal: "cat", difficulty: "advanced", viralScore: 89 },
        { title: "수술 직후나 중증 질환 회복기를 위한 고열량 회복식(a/d)", description: "적은 양으로도 높은 에너지를 공급하고 튜브 급여가 가능하도록 부드러운 유동식 형태를 띤 응급/회복용 캔.", tags: ["회복기","응급식"], animal: "both", difficulty: "basic", viralScore: 86 },
        { title: "특정 처방식을 평생 급여해도 안전할까? 급여 기간의 진실", 요로결석 용해용 처방식 등 단기간만 급여해야 하는 치료식과 신장 처방식처럼 평생 유지해야 하는 관리식의 차이.", tags: ["급여기간","장기급여"], animal: "both", difficulty: "advanced", viralScore: 92 },
        { title: "기호성 최악? 맛없는 처방식을 잘 먹게 하는 수의사의 꿀팁", description: "아파서 식욕이 떨어진 환자에게 전자레인지 데우기, 육수 섞기 등 처방식의 풍미를 높여 거부감을 줄이는 방법.", tags: ["기호성","식욕부진"], animal: "both", difficulty: "basic", viralScore: 96 },
        { title: "대장염과 변비에 특화된 고반응성 식이섬유(Fibre Response) 처방식", description: "차전자피 등 장운동을 촉진하고 수분을 머금는 특수 섬유소를 배합하여 변비 고양이의 배변을 돕는 처방식.", tags: ["식이섬유처방","변비"], animal: "cat", difficulty: "intermediate", viralScore: 87 },
        { title: "곤충 단백질을 활용한 새로운 저알레르기 처방식의 등장", description: "기존 육류 단백질에 알레르기가 있는 동물을 위해 교차 반응이 없는 동애등에 단백질로 만든 처방식의 장점.", tags: ["저알레르기","곤충사료"], animal: "both", difficulty: "intermediate", viralScore: 81 },
        { title: "단순 급여를 넘어선 처방식 기반의 체중 관리 프로그램 성공기", description: "동물병원 수의사와 함께 목표 체중을 설정하고 주기적으로 처방식 급여량을 모니터링하여 다이어트에 성공하는 과정.", tags: ["체중관리프로그램","비만클리닉"], animal: "both", difficulty: "basic", viralScore: 79 },
        { title: "처방식 효과를 100% 떨어뜨리는 치명적인 실수, '간식 투여'", description: "아무리 좋은 가수분해 사료나 결석 사료를 먹이더라도 시판 간식을 함께 먹이면 처방식의 치료 효과가 무용지물이 되는 이유.", tags: ["간식제한","처방식실패"], animal: "both", difficulty: "basic", viralScore: 98 },
        { title: "주기적인 혈액 검사와 연계한 처방식 모니터링의 중요성", description: "처방식을 바꾼 후 BUN/Creatinine 등 실제 질환 관련 수치가 어떻게 개선되었는지 수의학적으로 평가하는 방법.", tags: ["처방식모니터링","혈액검사"], animal: "both", difficulty: "advanced", viralScore: 85 },
        { title: "일반 사료와 다른 처방식 맞춤형 혈액 검사 해석법", description: "처방식 급여 중인 환자의 검사 결과를 해석할 때, 식단 변화가 미치는 영향을 고려하여 건강 상태를 정확히 평가하는 방법.", tags: ["혈액검사연계","검사결과해석"], animal: "both", difficulty: "advanced", viralScore: 82 },
        { title: "위장 장애 없이 부드러운 처방식 전환법", description: "질환으로 예민해진 소화기를 배려해 새로운 처방식으로 부작용 없이 서서히 교체하는 수의학적 프로토콜.", tags: ["처방식전환법","소화불량예방"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "성공적인 처방식 치료를 위한 보호자 필수 교육 가이드", description: "동물병원에서 제공해야 할 처방식의 올바른 급여 목적과 방법, 그리고 보호자가 반드시 지켜야 할 주의사항.", tags: ["보호자교육","처방가이드"], animal: "both", difficulty: "intermediate", viralScore: 86 },
        { title: "장기적인 처방식 급여가 부를 수 있는 잠재적 부작용 및 모니터링", description: "특정 영양소를 과도하게 제한하거나 보충하는 처방식의 장기 급여 시 발생할 수 있는 영양 불균형 문제와 예방책.", tags: ["장기급여부작용","영양불균형"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "처방식을 거부하는 환자를 위한 수액 및 대체 요법", description: "생존이 걸린 질환에서 끝내 처방식을 거부할 때 고려할 수 있는 피하 수액, 식욕 촉진제, 영양 튜브 등 대안적 접근.", tags: ["대체요법","식욕부진대처"], animal: "both", difficulty: "advanced", viralScore: 94 }
      ]
    },
    {
      id: "vet-preventive",
      name: "예방의학",
      icon: "🛡️",
      topics: [
        { title: "강아지와 고양이 연령별 필수 예방접종 스케줄", description: "코어 백신과 논코어 백신의 종류, 기초 접종부터 매년 추가 접종까지 생애 주기별 필수 백신 가이드.", tags: ["예방접종스케줄","백신"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "내외부 구충제 완벽 가이드: 기생충 종류와 약물 선택", description: "심장사상충, 진드기, 회충 등 기생충의 구별과 스팟온(바르는 약), 츄어블(먹는 약) 구충제별 장단점.", tags: ["구충제","기생충예방"], animal: "both", difficulty: "basic", viralScore: 92 },
        { title: "중성화 수술의 득과 실: 최적의 시기와 의학적 근거", description: "질병 예방(유선종양, 자궁축농증) 효과와 비만 등 부작용, 그리고 수의학계의 최신 중성화 시기 권장 사항.", tags: ["중성화","예방수술"], animal: "both", difficulty: "intermediate", viralScore: 96 },
        { title: "질병을 조기에 발견하는 반려동물 연령별 건강검진 항목", description: "기본 혈액검사부터 초음파, 엑스레이, SDMA 등 나이에 따라 추가해야 할 필수 건강검진 프로토콜.", tags: ["건강검진","조기진단"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "마이크로칩(동물등록) 시술, 정말 안전하고 필수적인가?", description: "내장형 칩 시술의 부작용에 대한 오해와 진실, 그리고 유기 및 분실 방지를 위한 칩의 중요성.", tags: ["마이크로칩","동물등록"], animal: "both", difficulty: "basic", viralScore: 85 },
        { title: "전신 마취 스케일링, 과연 안전할까? 위험성과 필요성", description: "치석으로 인한 전신 질환 예방 효과와 마취 전 검사를 통한 안전한 마취 스케일링 진행 과정.", tags: ["스케일링","치과예방"], animal: "both", difficulty: "intermediate", viralScore: 94 },
        { title: "만병의 근원 비만, 체계적인 예방과 집에서의 관리법", description: "비만이 유발하는 관절염, 당뇨 등의 합병증과 객관적인 BCS 평가를 통한 식단 및 운동 조절 계획.", tags: ["비만예방","다이어트"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "여름철 소리 없는 암살자, 열사병 응급 처치와 예방", description: "단두종에게 특히 치명적인 열사병의 전조 증상과 자동차 방치 위험성, 체온을 낮추는 올바른 쿨링 방법.", tags: ["열사병","여름건강"], animal: "both", difficulty: "intermediate", viralScore: 95 },
        { title: "겨울철 산책 주의보, 동상과 저체온증 예방 가이드", description: "눈길 염화칼슘으로 인한 발바닥 화상 예방과 실외견의 보온 조치, 겨울철 짧고 안전한 산책 요령.", tags: ["동상","겨울건강"], animal: "dog", difficulty: "basic", viralScore: 86 },
        { title: "하루 3분 양치질이 반려동물의 수명을 3년 늘리는 이유", description: "강아지와 고양이 전용 치약 선택법과 양치질을 극도로 싫어하는 동물을 위한 단계별 양치 적응 훈련법.", tags: ["양치질","구강관리"], animal: "both", difficulty: "basic", viralScore: 93 },
        { title: "풀밭 산책 전 필수, 살인 진드기(벼룩) 감염 예방과 대처법", description: "진드기 기피제의 올바른 사용법과 산책 후 진드기가 붙었을 때 핀셋으로 안전하게 제거하는 방법.", tags: ["벼룩예방","진드기"], animal: "both", difficulty: "basic", viralScore: 94 },
        { title: "안전한 야외 활동을 위한 산책 전 체크리스트 5가지", description: "온도 체크, 하네스 점검, 인식표 확인 등 사고 없는 산책을 위해 외출 전 확인해야 할 필수 사항들.", tags: ["산책체크리스트","야외활동"], animal: "dog", difficulty: "basic", viralScore: 82 },
        { title: "집 안에 두면 절대 안 되는 반려동물 치명적 유해 식물 10선", description: "백합, 튤립, 알로에 등 고양이와 강아지가 씹었을 때 급성 신부전이나 중독을 일으키는 관엽 식물 리스트.", tags: ["유해식물","중독예방"], animal: "both", difficulty: "basic", viralScore: 98 },
        { title: "슬개골 탈구를 막는 실내 환경: 미끄럼 방지와 발바닥 관리", description: "강아지의 관절을 보호하는 매트 시공, 발톱 및 발바닥 털 관리의 중요성과 올바른 발톱 깎기 노하우.", tags: ["발바닥관리","슬개골탈구예방"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "응급 수혈을 대비한 강아지, 고양이 혈액형 검사의 중요성", description: "DEA 1.1과 A/B/AB형 등 반려동물의 혈액형 종류와 첫 수혈 부작용을 막기 위한 사전 검사의 필요성.", tags: ["혈액형","수혈대비"], animal: "both", difficulty: "advanced", viralScore: 83 },
        { title: "반려동물과 해외여행(검역) 시 필요한 예방접종과 서류 준비", description: "광견병 항체가 검사, 마이크로칩, 영문 건강증명서 등 국가별로 복잡한 동물 검역 절차와 타임라인.", tags: ["여행서류","검역"], animal: "both", difficulty: "intermediate", viralScore: 80 },
        { title: "시력과 청력이 떨어진 노령견/묘를 위한 가정 내 안전 가이드", description: "모서리 보호대, 낙상 방지 펜스, 일정한 가구 배치 등 노령 동물이 다치지 않게 배려하는 환경 조성법.", tags: ["노령가정안전","시니어케어"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "집에서 손쉽게 확인하는 소변 스틱 검사와 건강 신호", description: "소변 색깔, 냄새, 횟수의 변화와 소변 검사 키트를 활용해 당뇨, 신장병, 방광염을 조기 발견하는 팁.", tags: ["소변검사","홈케어"], animal: "both", difficulty: "intermediate", viralScore: 89 },
        { title: "동물병원 방문 시 심장 청진을 반드시 요구해야 하는 이유", description: "무증상 심장병(이첨판 폐쇄부전증 등)의 조기 발견을 위한 심잡음 청진의 중요성과 수의사의 역할.", tags: ["심장청진","심장병예방"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "반려동물 화재 등 재난 상황 발생 시 대피 메뉴얼", description: "이동장 훈련, 비상용 펫 서바이벌 키트 준비, 반려동물 구출 요청 스티커 부착 등 생명을 살리는 재난 대비법.", tags: ["화재대비","재난대피"], animal: "both", difficulty: "basic", viralScore: 92 },
        { title: "봄, 여름, 가을, 겨울 계절별로 주의해야 할 건강 관리법", description: "봄철 꽃가루 알레르기부터 가을 털갈이, 겨울 호흡기 질환까지 계절의 변화에 맞춘 맞춤형 예방 가이드.", tags: ["계절별건강","사계절관리"], animal: "both", difficulty: "basic", viralScore: 84 },
        { title: "품종 특이적 유전병 예측을 위한 유전자(DNA) 검사 활용법", description: "다낭성신장질환(PKD), 진행성망막위축증(PRA) 등 품종별 유전 질환을 미리 알고 예방적 관리에 돌입하는 방법.", tags: ["유전자검사","유전병"], animal: "both", difficulty: "advanced", viralScore: 81 },
        { title: "인기 품종(말티즈, 푸들, 먼치킨 등) 입양 전 알아야 할 주의 질환", description: "특정 견종과 묘종이 유전적으로 취약한 질병 리스트와 이를 예방하거나 대비하기 위한 보호자의 마음가짐.", tags: ["품종별주의","입양전체크"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "반려동물 실비 보험 가입 전 꼭 확인해야 할 보장 내역", description: "슬개골 탈구, 치과 질환 등 다빈도 질병의 보장 여부와 면책 기간, 자기부담금을 고려한 펫보험 현명하게 고르기.", tags: ["반려동물보험","펫보험"], animal: "both", difficulty: "intermediate", viralScore: 89 },
        { title: "건강검진의 핵심, 정기 혈액검사 수치(BUN, ALT 등) 읽는 법", description: "신장, 간, 염증 수치 등 보호자도 기본적으로 알아두면 수의사와 상담할 때 큰 도움이 되는 혈액검사 결과 해석법.", tags: ["정기혈액검사","검사결과"], animal: "both", difficulty: "advanced", viralScore: 86 },
        { title: "잔병치레를 막는 일상 속 면역력 강화 5가지 습관", description: "규칙적인 산책, 양질의 수면, 스트레스 최소화, 영양 밸런스 등 항체 형성과 면역력을 높여주는 근본적인 관리.", tags: ["면역력강화","기초체력"], animal: "both", difficulty: "basic", viralScore: 85 },
        { title: "실내 공기 질과 환경 독소가 반려동물 호흡기에 미치는 악영향", description: "향초, 디퓨저, 섬유유연제 속 화학 물질이 후각이 예민한 개와 고양이에게 유발하는 천식과 만성 기관지염.", tags: ["환경독소","호흡기건강"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "나이와 질환에 맞는 올바른 영양제(보조제) 선택 가이드", description: "관절, 유산균, 오메가3 등 넘쳐나는 영양제 시장에서 과다 복용 부작용을 피하고 진짜 필요한 제품만 고르는 안목.", tags: ["영양제가이드","보조제"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "관절 무리 없는 강아지 맞춤형 실내외 운동 처방전", description: "슬개골이 안 좋은 아이, 비만인 아이를 위한 수영, 경사로 걷기, 어질리티 등 맞춤형 근력 강화 운동법.", tags: ["운동처방","재활운동"], animal: "dog", difficulty: "intermediate", viralScore: 84 },
        { title: "고양이 방광염의 주범, 1순위 스트레스 관리와 환경 풍부화", description: "영역 동물인 고양이의 본능을 충족시켜주는 캣타워, 스크래쳐 배치와 사냥놀이를 통한 특급 스트레스 해소 솔루션.", tags: ["스트레스관리","환경풍부화"], animal: "cat", difficulty: "basic", viralScore: 95 }
      ]
    },
    {
      id: "vet-dental",
      name: "치과",
      icon: "🦷",
      topics: [
        { title: "유치 잔존의 위험성: 부정교합과 치석의 지름길", description: "생후 6~7개월 이후에도 빠지지 않은 유치가 영구치의 성장을 방해하고 구강 건강을 악화시키는 이유.", tags: ["유치잔존","이갈이"], animal: "dog", difficulty: "basic", viralScore: 88 },
        { title: "입 안에 생긴 혹, 양성 에폴리스와 악성 구강 종양 감별", description: "잇몸에 생기는 혹의 종류와 구강 흑색종, 편평상피암 등 치명적인 악성 종양의 조기 발견 중요성.", tags: ["구강종양","치과질환"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "단단한 뼈 간식이 부르는 참사, 치아 골절(파절) 대처법", description: "개껌이나 동결건조 뼈간식을 씹다 이빨이 부러져 신경이 노출됐을 때의 극심한 통증과 신경 치료 과정.", tags: ["치아골절","치과응급"], animal: "dog", difficulty: "intermediate", viralScore: 95 },
        { title: "플라그에서 치석으로, 양치질 골든타임 48시간의 비밀", description: "음식물 찌꺼기가 플라그를 거쳐 딱딱한 치석으로 굳어지는 과정과 이를 막기 위한 이틀에 한 번 양치의 원리.", tags: ["치석형성","양치질"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "고양이 치과 질환 1위, 치아 흡수성 병변(FORL)의 모든 것", description: "멀쩡해 보이던 이빨이 잇몸 아래에서 서서히 녹아내리는 극심한 통증의 원인과 유일한 완치법인 전체 발치.", tags: ["FORL","고양이치과"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "바르는 치약, 먹는 덴탈 간식, 정말 양치질을 대체할 수 있을까?", description: "물리적 마찰(칫솔질) 없이 화학적 성분만으로 치석을 예방하려는 덴탈 제품들의 맹점과 보조적 한계.", tags: ["덴탈간식","구강관리"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "반려동물 구취의 5가지 원인: 단순 입냄새부터 신장병까지", description: "구강 내 세균 증식 외에도 위장관 질환, 신장 기능 저하, 당뇨 등이 뿜어내는 특유의 악취로 건강 상태 파악하기.", tags: ["구취원인","입냄새"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "일반 진료와 치과 전문 수의사(수의치과) 진료의 차이점", description: "단순 스케일링을 넘어 치과 방사선 촬영, 신경 치료, 복잡한 발치 등 전문적인 장비와 기술을 요하는 치과 진료.", tags: ["치과전문의","동물병원"], animal: "both", difficulty: "intermediate", viralScore: 82 },
        { title: "마시는 양치질, 워터 첨가제의 성분 안전성과 실제 효과", description: "식수에 타서 마시는 구강 청결제의 작용 원리와 자일리톨, 알코올 등 피해야 할 위험 성분 분석.", tags: ["워터첨가제","구강청결제"], animal: "both", difficulty: "basic", viralScore: 85 },
        { title: "턱이 좁은 소형견(말티즈, 요키)이 유독 치과 질환에 취약한 이유", description: "작은 턱뼈에 많은 치아가 빽빽하게 자라나 치석이 쉽게 쌓이고 치주염의 진행 속도가 빠른 유전적 원인.", tags: ["소형견치과","구강구조"], animal: "dog", difficulty: "intermediate", viralScore: 87 },
        { title: "안전한 마취 스케일링을 위한 사전 검사와 수의학적 프로토콜", description: "노령견도 안전하게 마취를 견딜 수 있도록 돕는 혈액검사, 흉부 엑스레이, 마취 모니터링 시스템의 중요성.", tags: ["마취스케일링","안전마취"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "반려동물도 치아 교정을 할까? 부정교합 치료 사례", description: "외모 목적이 아닌, 아래턱 송곳니가 입천장을 찌르는 등 통증과 감염을 유발하는 부정교합의 의학적 교정 치료.", tags: ["치아교정","부정교합"], animal: "both", difficulty: "advanced", viralScore: 79 },
        { title: "어려운 발치 수술 후 보호자가 챙겨야 할 식단과 홈케어", description: "발치 부위의 출혈과 염증을 막기 위한 습식 사료 급여 요령, 넥카라 착용, 그리고 항생제 진통제 복약 지도.", tags: ["발치후관리","구강수술"], animal: "both", difficulty: "intermediate", viralScore: 86 },
        { title: "집에서 쉽게 따라 하는 반려동물 구강 자가 검진(Flip the Lip)", description: "입술을 들쳐 잇몸 색깔, 치석 정도, 부종 등을 확인하여 치과 진료 시기를 놓치지 않는 홈체크 노하우.", tags: ["구강검사법","자가검진"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "방치하면 턱뼈가 녹는다, 치은염에서 치주염으로의 악화 단계", description: "가벼운 잇몸 염증(치은염)이 치아를 지지하는 뼈를 파괴하는 치주염으로 진행되는 4단계 과정 상세 분석.", tags: ["치은염단계","치주염"], animal: "both", difficulty: "intermediate", viralScore: 92 },
        { title: "이빨을 뽑지 않고 살리는 수의 치수 치료(신경 치료)의 세계", description: "부러진 송곳니나 어금니를 무조건 뽑지 않고 레진과 크라운을 씌워 기능을 유지하게 만드는 첨단 수의 치과 기술.", tags: ["치수치료","신경치료"], animal: "both", difficulty: "advanced", viralScore: 84 },
        { title: "구강 미생물 생태계를 건강하게, 구강 유산균(건강식품)의 효과", description: "장 유산균과 달리 입안에 정착하여 유해균의 증식을 억제하고 구취를 줄여주는 최신 구강 프로바이오틱스 트렌드.", tags: ["치아건강식품","구강유산균"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "마취 없는 '무마취 스케일링'이 치아를 더 망가뜨리는 치명적 이유", description: "잇몸 아래 숨은 치석(치은연하치석)을 제거하지 못하고 치아 표면만 긁어 상처를 내어 오히려 세균 번식을 돕는 위험성.", tags: ["무마취스케일링위험","스케일링진실"], animal: "both", difficulty: "basic", viralScore: 98 },
        { title: "침을 질질 흘리는 고양이, 만성 구내염의 끔찍한 고통과 전발치", description: "면역 체계의 이상으로 치태에 극도로 과민 반응하여 입안 전체가 허는 난치성 구내염의 유일한 해법.", tags: ["고양이구내염","전발치"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "칫솔, 손가락 칫솔, 거즈: 우리 아이에게 맞는 치아 관리 용품은?", description: "아이의 구강 구조와 양치 거부감 정도에 따라 플라그 제거 효율이 가장 높은 도구를 단계별로 선택하는 방법.", tags: ["치아관리용품비교","칫솔선택"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "어린 강아지부터 노령견까지, 연령별 맞춤형 치과 관리 전략", description: "유치 관리기, 스케일링 권장기, 치아 소실기 등 생애 주기에 따라 달라지는 구강 건강 포인트 짚어보기.", tags: ["연령별치과관리","생애주기치과"], animal: "both", difficulty: "intermediate", viralScore: 85 },
        { title: "천연 칫솔이라는 오해, 수제 뼈 간식 급여 시 주의사항", description: "딱딱한 뼈가 플라그를 제거해 준다는 믿음의 이면에 숨겨진 치아 파절, 장폐색, 천공 등 무서운 응급 상황들.", tags: ["뼈간식위험","치아파절"], animal: "dog", difficulty: "intermediate", viralScore: 94 },
        { title: "눈에 보이지 않는 뿌리를 보는 창, 치과 엑스레이의 필수성", description: "겉보기엔 멀쩡한 이빨이 엑스레이 상에서는 뿌리에 농양이 찼거나 턱뼈가 녹아내린 상태일 수 있는 이유.", tags: ["치과엑스레이","정밀진단"], animal: "both", difficulty: "advanced", viralScore: 90 },
        { title: "적절한 유치 발치 시기: 마취 횟수를 줄이는 영리한 타이밍", description: "중성화 수술 등 다른 수술을 위해 마취할 때 잔존 유치를 함께 뽑아 마취의 부담과 비용을 줄이는 방법.", tags: ["유치발치시기","마취최소화"], animal: "dog", difficulty: "intermediate", viralScore: 87 },
        { title: "양치질 중 잇몸 출혈, 계속 닦아야 할까 멈춰야 할까?", description: "피가 나는 것은 이미 치은염이 있다는 증거이므로 부드럽게 계속 닦아 염증을 빼내야 한다는 치과학적 진실.", tags: ["잇몸출혈원인","양치질피"], animal: "both", difficulty: "basic", viralScore: 93 },
        { title: "노랗고 까맣게 변한 이빨, 단순 착색일까 신경 괴사일까?", description: "외부 색소에 의한 단순 착색과 강한 충격으로 신경이 죽어 치아 내부에서 검게 변색된 치아를 감별하는 법.", tags: ["치아변색","신경괴사"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "건강한 핑크빛 잇몸과 촉촉함, 구강 건강의 지표 3가지", description: "잇몸의 색, 모세혈관 재충혈 시간(CRT), 타액의 끈적임 정도를 통해 구강 건강뿐 아니라 전신 건강의 적신호 알아채기.", tags: ["구강건강지표","건강체크"], animal: "both", difficulty: "basic", viralScore: 86 },
        { title: "동물병원 치과 수술 비용이 사람보다 비싼 진짜 이유", description: "의료보험 미적용뿐만 아니라 마취 전문의, 호흡 마취 장비, 모니터링 비용이 필수적으로 포함되는 동물 진료비의 구조.", tags: ["치과수술비용","진료비이해"], animal: "both", difficulty: "intermediate", viralScore: 92 },
        { title: "효소 치약 vs 클로르헥시딘 치약, 상황에 따른 성분 분석", description: "플라그 분해 효소가 든 데일리 치약과 잇몸 염증 치료 목적으로 단기간 사용하는 소독약 성분 치약의 올바른 사용 구분.", tags: ["치약성분분석","치약선택"], animal: "both", difficulty: "advanced", viralScore: 85 },
        { title: "매일 저녁 3분, 전쟁 같은 양치 시간을 평화로운 루틴으로 만들기", description: "간식 보상, 긍정 강화, 얼굴 만지기 둔감화 훈련을 통해 양치질을 놀이처럼 인식하게 만드는 행동학적 접근법.", tags: ["치아관리루틴","긍정강화양치"], animal: "both", difficulty: "basic", viralScore: 95 }
      ]
    },
    {
      id: "vet-emergency",
      name: "응급의학",
      icon: "🚑",
      topics: [
        { title: "골든타임 3분, 생명을 살리는 반려동물 심폐소생술(CPR) 방법", description: "심정지 상태 확인 후 흉부 압박 위치, 깊이, 속도 및 인공호흡 비율 등 정확한 CPR 수행 메뉴얼.", tags: ["CPR","심폐소생술"], animal: "both", difficulty: "advanced", viralScore: 98 },
        { title: "포도, 자일리톨 섭취 등 독극물 응급 대처와 구토 유발 주의사항", description: "위험 물질을 삼켰을 때 2시간 내 병원 내원과, 집에서 과산화수소로 구토를 유발하면 안 되는 물질 구분하기.", tags: ["독극물대처","오식응급"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "교통사고 발생 시 2차 손상을 막는 안전한 이동 방법", description: "골절이나 내부 장기 출혈이 의심될 때 들것이나 단단한 판을 이용해 척추를 고정하고 이송하는 응급처치.", tags: ["교통사고","외상응급"], animal: "both", difficulty: "intermediate", viralScore: 95 },
        { title: "갑작스러운 경련과 발작 발생 시 보호자의 대처 행동 지침", description: "동물을 억압하지 않고 주변 위험 물건 치우기, 동영상 촬영, 그리고 발작 지속 시간(Status Epilepticus) 체크의 중요성.", tags: ["경련발작","신경응급"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "대형견의 치명적인 초응급 질환, 위염전(GDV) 의심 증상", description: "밥을 급하게 먹은 후 배가 빵빵해지고 헛구역질을 하는 위확장-염전의 위험성과 즉각적인 외과 수술의 필요성.", tags: ["GDV","위염전"], animal: "dog", difficulty: "advanced", viralScore: 94 },
        { title: "수컷 고양이가 화장실을 들락거리며 울부짖을 때 (요도 폐색)", description: "급성 신부전과 심정지를 유발하는 하부요로기계 폐색 증상 인지와 24시간 내 카테터 장착의 골든타임.", tags: ["요도폐색","고양이응급"], animal: "cat", difficulty: "advanced", viralScore: 98 },
        { title: "산책 중 뱀에 물렸을 때의 치명성과 응급 처방", description: "물린 부위 확인, 절대 뛰지 않게 안아서 이동하기, 지혈대 사용 금지 등 독사 교상 시 생존율을 높이는 대처법.", tags: ["뱀물림","교상응급"], animal: "dog", difficulty: "intermediate", viralScore: 90 },
        { title: "아나필락시스 쇼크를 유발하는 벌 쏘임과 곤충 교상 증상", description: "얼굴이 심하게 붓고 호흡 곤란이 오는 급성 알레르기 반응(아나필락시스)과 에피네프린 투여 등 병원 응급 처치.", tags: ["벌쏘임","아나필락시스"], animal: "both", difficulty: "intermediate", viralScore: 92 },
        { title: "발톱 깎다 피가 나거나 외상 출혈 시 올바른 압박 지혈법", description: "깨끗한 거즈로 상처 부위를 5분 이상 강하게 직접 압박하는 지혈의 기본 원칙과 지혈 가루(지혈제) 사용법.", tags: ["출혈지혈","외상응급"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "보호자라면 꼭 구비해야 할 '반려동물 전용 응급 구급상자(키트)' 리스트", description: "체온계, 붕대, 거즈, 생리식염수, 핀셋, 넥카라 등 위급 상황에서 즉시 사용할 수 있는 필수 응급 용품들.", tags: ["응급키트","가정구급함"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "뜨거운 물이나 전기장판에 의한 화상 응급 처치 방법", description: "얼음물을 직접 대지 않고 시원한 흐르는 물로 15분 이상 열기를 식혀 조직 손상을 최소화하는 쿨링 요령.", tags: ["화상응급","열상대처"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "간식이나 장난감이 목에 걸렸을 때 (하임리히 유도법)", description: "호흡을 못 하고 청색증이 온 경우 동물의 크기에 맞춰 복부를 압박하거나 등을 두드려 이물을 빼내는 하임리히법.", tags: ["질식대처","하임리히"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "여름철 바다나 수영장 익수(물놀이) 사고 시 응급 대처와 건성 익사 주의", description: "물 밖으로 꺼낸 후 기도를 확보하는 방법과, 구조 후 몇 시간 뒤 폐에 찬 물 때문에 발생하는 2차 건성 익사의 위험성.", tags: ["익수사고","수영장응급"], animal: "dog", difficulty: "advanced", viralScore: 93 },
        { title: "전선 물어뜯기로 인한 전기 감전 쇼크 대처와 구강 화상", description: "강아지가 전선을 씹었을 때 전원을 먼저 차단하는 안전 수칙과 폐수종 등 지연성 합병증을 막기 위한 병원 관찰.", tags: ["전기감전","전선화상"], animal: "both", difficulty: "intermediate", viralScore: 90 },
        { title: "고층 아파트에서 떨어진 고양이, 하이라이즈 신드롬(High-Rise Syndrome)", description: "추락 시 골절뿐만 아니라 기흉, 구개열(입천장 파열), 방광 파열 등 보이지 않는 내부 장기 손상을 확인하는 응급 진료.", tags: ["고양이추락","기흉응급"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "집 쥐약을 먹은 반려동물, 쥐약(항응고제) 중독의 공포", description: "비타민 K 길항제로 작용해 몸속 출혈이 멈추지 않아 빈혈로 사망에 이르는 설치류 독극물 섭취의 끔찍한 결과와 해독 치료.", tags: ["설치류독극물","쥐약중독"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "사람 먹는 감기약, 진통제(타이레놀, 이부프로펜)가 동물에게 치명적인 이유", description: "간 독성과 위장관 천공을 유발하는 사람 약물의 위험성과 동물 전용 해열진통제를 반드시 처방받아야 하는 이유.", tags: ["응급약물","타이레놀중독"], animal: "both", difficulty: "basic", viralScore: 98 },
        { title: "핏기가 사라진 창백한 잇몸, 쇼크(Shock) 상태의 전조 증상 인지하기", description: "심한 출혈, 심장 기능 저하, 패혈증 등으로 조직에 산소 공급이 안 될 때 나타나는 모세혈관 재충혈 시간(CRT) 지연 현상.", tags: ["쇼크증상","창백한잇몸"], animal: "both", difficulty: "advanced", viralScore: 92 },
        { title: "백신 접종 직후 발생하는 급성 알레르기 쇼크 관찰 시간", description: "예방접종 후 병원에 15분 이상 머물러야 하는 이유와 집에 돌아가서 안면 부종, 구토, 호흡 곤란을 살피는 요령.", tags: ["알레르기쇼크","백신부작용"], animal: "both", difficulty: "intermediate", viralScore: 89 },
        { title: "다리가 부러졌을 때 부목 고정(Splint) 요령과 절대 주의사항", description: "뼈가 튀어나온 개방성 골절과 폐쇄성 골절의 차이, 억지로 뼈를 맞추려 하지 않고 잡지 등 단단한 물체로 임시 고정하는 법.", tags: ["골절응급","부목고정"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "단두종(페키니즈, 시츄)에게 흔한 안구 탈출(안구 돌출) 응급 처치", description: "가벼운 충격이나 목줄 당김에도 눈알이 빠질 수 있는 단두종의 특성과 젖은 거즈로 덮어 즉시 안과 수술을 요하는 상황.", tags: ["안구탈출","단두종응급"], animal: "dog", difficulty: "advanced", viralScore: 95 },
        { title: "정상 체온 범위를 벗어난 심각한 고열과 저체온증의 원인", description: "38~39도를 넘는 40도 이상의 고열(감염, 열사병)과 37도 이하의 저체온증(쇼크, 마취 후)이 신체 장기에 미치는 파괴력.", tags: ["체온이상","체온계사용"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "단 10분 만에 뇌가 익어버리는 한여름 자동차 내 방치 사고", description: "창문을 살짝 열어두거나 그늘에 주차해도 차 안 온도가 급격히 상승해 끔찍한 열사병으로 사망하는 온실 효과의 위험성.", tags: ["자동차내방치","여름열사병"], animal: "both", difficulty: "basic", viralScore: 99 },
        { title: "집 근처 24시간 응급 동물병원을 미리 알아두어야 하는 이유", description: "새벽에 발생한 위급 상황에서 병원을 찾느라 허비하는 시간을 막기 위해 야간 수의사가 상주하는 병원 리스트를 저장해 두기.", tags: ["응급병원찾기","24시병원"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "산책길 독버섯, 두꺼비 중독 등 야생 동식물 접촉의 위험", description: "봄/여름철 야외 활동 중 호기심에 핥거나 먹은 두꺼비 독액과 독버섯이 유발하는 극심한 환각, 구토, 신경 마비 증상.", tags: ["독버섯중독","야생동물접촉"], animal: "dog", difficulty: "intermediate", viralScore: 86 },
        { title: "제초제나 부동액(에틸렌 글리콜) 중독의 끔찍한 말로", description: "단맛이 나 동물이 핥아 먹기 쉬운 부동액이 단 몇 방울만으로도 급성 신부전을 일으켜 죽음에 이르게 하는 공포의 성분.", tags: ["제초제중독","부동액중독"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "심한 설사와 구토 후 필수적인 수액 치료(IV/SC)의 중요성", description: "탈수로 인해 끈적해진 혈액을 희석시키고 전해질 불균형을 교정하여 장기 손상을 막는 입원 정맥 수액과 피하 수액의 차이.", tags: ["응급수액","탈수대처"], animal: "both", difficulty: "intermediate", viralScore: 85 },
        { title: "호흡 곤란(개구 호흡) 시 절대 스트레스 주지 말고 산소 공급하기", description: "고양이가 입을 벌리고 헐떡이거나 혀가 파래질 때 무리한 검사보다 시원하고 안정된 산소방(Oxygen cage) 처치가 최우선인 이유.", tags: ["응급호흡관리","개구호흡"], animal: "both", difficulty: "advanced", viralScore: 93 },
        { title: "지네, 거미 등 독충에 물렸을 때 나타나는 국소 및 전신 증상", description: "물린 부위의 심한 부종, 통증, 괴사와 더불어 전신적인 발열이나 쇼크가 동반될 수 있는 독충 교상의 동물병원 처치.", tags: ["독충에물림","곤충교상"], animal: "both", difficulty: "intermediate", viralScore: 84 },
        { title: "아기가 떨어뜨린 약이나 장난감을 삼킨 유아-반려동물 사고", description: "영유아가 있는 가정에서 아이가 무심코 준 사람 음식이나 작은 레고 블록 등을 반려견이 삼켜 발생하는 가정 내 흔한 응급 콜.", tags: ["유아실수섭취","가정내사고"], animal: "dog", difficulty: "basic", viralScore: 90 }
      ]
    },
    {
      id: "vet-senior",
      name: "노령동물학",
      icon: "👴",
      topics: [
        { title: "밤새 돌아다니며 짖는 노령견, 인지기능장애증후군(치매) 대처법", description: "구석에 갇히거나 주인을 못 알아보는 치매 증상 평가와 항산화제, 처방식, 항불안 약물을 통한 삶의 질 개선.", tags: ["인지기능장애","치매"], animal: "dog", difficulty: "advanced", viralScore: 95 },
        { title: "다리를 절뚝이는 늙은 반려동물, 퇴행성 관절염 통증 관리", description: "엑스레이 상 뼈가 닳은 골관절염 환자를 위한 진통소염제(NSAIDs), 연골 주사, 레이저 물리 치료 및 체중 조절.", tags: ["관절염관리","퇴행성질환"], animal: "both", difficulty: "intermediate", viralScore: 89 },
        { title: "나이 든 고양이가 밥을 잘 먹는데도 살이 빠지는 이유", description: "갑상선기능항진증, 만성신장병, 당뇨, 소화기 림프종 등 체중 감소를 유발하는 노령묘의 대표적인 4대 질환 감별.", tags: ["노령묘체중감소","노령고양이"], animal: "cat", difficulty: "advanced", viralScore: 96 },
        { title: "근육이 빠져 앙상해지는 근감소증(Sarcopenia) 예방과 단백질 급여", description: "노화로 인한 근손실을 막기 위해 신장 기능이 허락하는 한 양질의 고단백 식단과 가벼운 운동이 필수적인 이유.", tags: ["근감소증","노령견단백질"], animal: "both", difficulty: "intermediate", viralScore: 91 },
        { title: "말 못 하는 노령 동물의 통증을 알아채는 미묘한 신호들", description: "잠이 늘고, 식욕이 줄고, 만지면 예민해지는 행동 변화가 단순한 노화가 아닌 질환으로 인한 극심한 통증의 표현일 수 있음.", tags: ["통증관리","노화증상"], animal: "both", difficulty: "basic", viralScore: 94 },
        { title: "나이가 많아도 수술과 마취를 견딜 수 있을까? 노령견 마취 위험성 평가", description: "ASA 등급 평가와 심장 초음파, 흉부 방사선, 철저한 혈액검사를 통해 마취 전 위험 요소를 통제하는 수의학적 접근.", tags: ["마취위험","노령견수술"], animal: "both", difficulty: "advanced", viralScore: 93 },
        { title: "평생 가리던 대소변을 못 가리는 노령 동물의 신체적, 정신적 원인", description: "방광 괄약근 약화, 척추 디스크로 인한 신경 마비, 혹은 인지 장애로 인한 배변 실수에 대처하는 기저귀 사용과 매트 배치.", tags: ["배변실수","괄약근약화"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "시력과 청력이 저하된 반려동물을 위한 감각 보완 환경 세팅", description: "가구 위치를 바꾸지 않고 냄새와 질감(서로 다른 러그)을 활용해 길을 안내하여 시야가 좁아진 환자의 불안감 덜어주기.", tags: ["시력청력저하","감각소실"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "치료가 불가능할 때, '삶의 질(Quality of Life)' 평가표 활용법", description: "식욕, 배변, 통증, 호흡, 행복감 등 5가지 지표를 점수화하여 보호자가 이성적으로 동물의 상태를 기록하고 평가하는 기준.", tags: ["삶의질평가","QOL"], animal: "both", difficulty: "advanced", viralScore: 98 },
        { title: "노화 방지를 돕는 필수 노령용 영양 보충제 베스트 5", description: "오메가3, 유산균, 관절 영양제, 항산화제(비타민 E, SAMe), 심장 보조제 등 노화 속도를 늦추고 장기를 보호하는 성분들.", tags: ["영양보충제","항산화제"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "무리하지 않는 노령견의 안전한 근력 강화 운동법", description: "산책 시간을 짧게 여러 번으로 나누고 평지 위주로 걷거나 수중 러닝머신을 활용해 관절 부담 없이 근육을 유지하는 재활.", tags: ["노령견운동","근력유지"], animal: "dog", difficulty: "basic", viralScore: 85 },
        { title: "인지기능 장애(치매)의 초기 징후, DISHAA 평가로 잡아내기", description: "방향 감각 상실(D), 상호작용 변화(I), 수면 패턴(S), 집안에서 길 잃음(H), 활동성(A), 불안(A)의 약자로 구성된 치매 진단법.", tags: ["치매초기징후","DISHAA"], animal: "dog", difficulty: "advanced", viralScore: 92 },
        { title: "불치병 환자의 편안한 이별을 준비하는 동물 호스피스 완화 치료", description: "수명 연장이 아닌 통증 완화, 호흡 안정, 영양 공급에 초점을 맞춰 남은 생을 편안하게 돕는 수의학적 호스피스 케어.", tags: ["호스피스케어","완화치료"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "가장 고통스러운 선택, 안락사 결정 기준과 펫로스 극복", description: "수의학적 윤리와 동물의 삶의 질을 바탕으로 안락사 시점을 논의하고, 이별 후 보호자의 심리적 상실감을 치유하는 과정.", tags: ["안락사결정","펫로스증후군"], animal: "both", difficulty: "advanced", viralScore: 99 },
        { title: "노령묘 사망 원인 1위, 신장 기능 보존을 위한 철저한 수분 관리", description: "건사료를 습식으로 바꾸고 집안 곳곳에 물그릇을 둬서 음수량을 늘리며, 필요시 피하 수액을 투여해 탈수를 막는 묘책.", tags: ["노령묘신장관리","수분관리"], animal: "cat", difficulty: "intermediate", viralScore: 94 },
        { title: "낮에 자고 밤에 우는 노령 동물의 수면 패턴 변화 교정", description: "생체 시계 교란으로 인한 주야간 역전 현상을 막기 위해 낮 동안 햇빛을 쬐고 멜라토닌 보조제를 활용하여 숙면 유도하기.", tags: ["수면패턴변화","생체시계"], animal: "both", difficulty: "intermediate", viralScore: 89 },
        { title: "기침하고 헐떡이는 노령견의 심장(이첨판 폐쇄부전증) 관리", description: "노령 소형견의 70%가 겪는 심장 판막 질환의 엑스레이, 심장 초음파 진단과 이뇨제, 강심제를 활용한 평생 내과적 약물 복용.", tags: ["노령심장관리","심장병약물"], animal: "dog", difficulty: "advanced", viralScore: 93 },
        { title: "면역력 저하로 찾아오는 노령 동물의 잦은 감염증 방어", description: "젊을 땐 이겨내던 피부 농피증, 방광염 등 가벼운 세균 감염이 노령기엔 패혈증으로 번질 수 있어 빠른 항생제 투여가 필요한 이유.", tags: ["면역력저하","노령감염증"], animal: "both", difficulty: "intermediate", viralScore: 86 },
        { title: "소화 효소가 줄어든 노령 동물의 식단: 소화 기능 감퇴에 대처하기", description: "딱딱한 사료를 불려 주거나 화식/습식으로 전환하고 프로바이오틱스와 소화 효소제를 첨가해 영양 흡수율을 극대화하는 팁.", tags: ["소화기능감퇴","노령식단"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "털이 푸석해지고 각질이 생기는 피모 변화, 단순 노화일까 호르몬 질환일까?", description: "피지 분비량 감소로 인한 자연스러운 털빠짐과 쿠싱, 갑상선 저하증 등 내분비 질환으로 인한 대칭성 탈모의 뚜렷한 차이.", tags: ["피모변화","내분비질환의심"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "마취가 부담스러운 노령견의 스케일링과 치과 관리 타협점", description: "심한 치주염으로 고통받지만 심장병으로 전신 마취가 불가능할 때 항생제와 펄스 요법을 이용해 염증과 통증만 조절하는 보존적 관리.", tags: ["노령치과관리","마취위험치과"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "노화하는 뇌세포를 깨우는 일상 속 인지 자극 활동(Nose Work)", description: "어려운 훈련 대신 후각을 활용한 간식 찾기 놀이나 새로운 산책 코스 탐험으로 뇌에 긍정적인 자극을 주어 치매를 지연시키는 훈련.", tags: ["인지자극활동","노즈워크"], animal: "dog", difficulty: "basic", viralScore: 85 },
        { title: "매일 먹어야 하는 한 움큼의 약, 투약 스트레스 줄이는 약물 관리 팁", description: "심장약, 관절약, 영양제 등 다약제 복용 환자에게 캡슐 씌우기, 필포켓 활용, 투약 보조제 섞기 등 구토 없이 꿀꺽 삼키게 하는 노하우.", tags: ["약물관리","투약스트레스"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "증상이 없어도 6개월마다 노령 정기 검진을 해야 하는 이유", description: "노화의 시계는 사람보다 7배 빠르므로, 1년 전 정상이었던 혈액 수치가 몇 달 만에 신부전 3기로 악화될 수 있는 속도전 대비 프로토콜.", tags: ["정기검진프로토콜","노령건강검진"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "뒷다리 힘이 풀린 노령견을 돕는 하네스, 휠체어 보조 기구 활용", description: "디스크나 관절염으로 일어서지 못하는 환자의 욕창을 예방하고 보행을 돕는 후지 보조 하네스와 맞춤형 휠체어의 놀라운 재활 효과.", tags: ["보조기구활용","강아지휠체어"], animal: "dog", difficulty: "intermediate", viralScore: 89 },
        { title: "후각 상실로 식욕을 잃은 동물을 위한 특급 식욕 촉진법", description: "냄새를 맡지 못해 밥을 거부할 때 사료를 전자레인지에 데워 향을 극대화하거나 닭육수, 캔 사료를 섞어 본능을 깨우는 식사 유도법.", tags: ["식욕촉진법","후각상실"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "이사나 새로운 가족 구성원이 노령 동물에게 미치는 치명적 스트레스", description: "환경 변화에 대한 적응력이 떨어진 노령견/묘에게 갑작스러운 이사나 아기 탄생이 면역계 교란과 질병 악화로 이어지는 과정 예방하기.", tags: ["환경적응","노령스트레스"], animal: "both", difficulty: "intermediate", viralScore: 86 },
        { title: "심장병 약이 신장을 망가뜨린다? 다장기 질환(Multi-organ disease) 딜레마", description: "심장병 치료를 위한 이뇨제가 신부전을 악화시킬 때 수의사가 두 장기 사이에서 아슬아슬하게 약물 용량을 조절하는 처방의 예술.", tags: ["다장기질환","약물딜레마"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "간병 지옥에 빠진 보호자를 위한 심리 케어와 돌봄 휴식(Respite care)", description: "밤낮없는 노령견 케어로 수면 부족과 우울증을 겪는 보호자의 '번아웃'을 방지하기 위해 가족 간 교대 간병과 동물병원 입원의 필요성.", tags: ["보호자심리케어","보호자번아웃"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "버림받은 늙은 천사, 노령 반려동물 입양이 주는 특별한 감동", description: "에너지 넘치는 새끼 강아지보다 조용하고 교감 능력이 뛰어난 유기 노령견을 가족으로 맞이했을 때 얻는 정서적 안정과 성숙한 반려 생활.", tags: ["노령반려동물입양","유기견입양"], animal: "both", difficulty: "basic", viralScore: 98 }
      ]
    },
    {
      id: "vet-dermatology",
      name: "피부과",
      icon: "🩹",
      topics: [
        { title: "피가 나도록 긁는 가려움증(소양감)의 3대 원인 감별", description: "기생충 감염, 알레르기(식이/환경), 세균/곰팡이 감염 등 강아지를 괴롭히는 가려움증의 근본 원인 찾기 프로토콜.", tags: ["가려움원인","피부병진단"], animal: "dog", difficulty: "intermediate", viralScore: 94 },
        { title: "하룻밤 새 짓무른 피부, 급성 습성 피부염(핫스팟)의 대처", description: "습한 여름철이나 목욕 후 덜 말렸을 때 세균 증식으로 인해 붉고 진물이 나는 급성 핫스팟의 소독과 건조 치료법.", tags: ["핫스팟","급성피부염"], animal: "dog", difficulty: "basic", viralScore: 90 },
        { title: "발사탕의 주범, 말라세지아 효모균(곰팡이) 감염의 특효약", description: "발가락 사이나 귀에서 시큼한 냄새를 유발하는 효모균 과다 증식의 원인(습기, 알레르기)과 항진균제 및 약용 샴푸 관리.", tags: ["효모감염","발사탕"], animal: "both", difficulty: "intermediate", viralScore: 93 },
        { title: "대칭성 탈모 vs 비대칭성 탈모, 털 빠지는 패턴으로 유추하는 질병", description: "몸 양쪽이 똑같이 빠지면 내분비(호르몬) 질환, 한쪽만 듬성듬성 빠지면 감염이나 긁어서 생긴 상처일 확률이 높은 탈모 감별법.", tags: ["탈모패턴","호르몬탈모"], animal: "both", difficulty: "advanced", viralScore: 88 },
        { title: "사람에게도 옮는 무서운 피부병, 고양이 링웜(피부사상충증)", description: "원형 탈모와 각질을 동반하며 면역력이 약한 어린 고양이와 보호자에게 전염되는 링웜의 길고 지루한 항진균 치료 완치기.", tags: ["링웜","인수공통전염병"], animal: "cat", difficulty: "intermediate", viralScore: 96 },
        { title: "스테로이드 없이 가려움 스위치만 끈다, 사이토포인트 주사와 아포퀠", description: "아토피 개들의 구세주로 불리는 표적 치료제들의 작용 기전과 간/신장 부작용 없이 평생 투여 가능한 최신 신약의 장점.", tags: ["사이토포인트","아포퀠"], animal: "dog", difficulty: "advanced", viralScore: 97 },
        { title: "음식 알레르기 원인 단백질을 찾는 8주간의 제거 식이(Elimination Diet)", description: "알레르기 검사에 의존하지 않고 가수분해 사료나 새로운 단백질원만 급여하며 증상이 호전되는지 확인하는 가장 정확한 진단법.", tags: ["제거식이","음식알레르기"], animal: "both", difficulty: "advanced", viralScore: 91 },
        { title: "피부병 약용 샴푸(클로르헥시딘, 마이코나졸) 올바른 적용 시간과 빈도", description: "세균이나 곰팡이를 죽이기 위해 약용 샴푸를 몸에 바르고 최소 10분 이상 방치해야 효과가 나타나는 수의 피부과 목욕 수칙.", tags: ["약용샴푸","피부관리"], animal: "both", difficulty: "basic", viralScore: 92 },
        { title: "귀에서 검은 귀지가 쏟아지고 가렵다면? 귀진드기 감염", description: "새끼 고양이나 다묘 가정에서 흔히 발생하며 커피 찌꺼기 같은 귀지를 동반하는 전염성 강한 귀진드기의 현미경 진단과 구충.", tags: ["귀진드기","기생충감염"], animal: "cat", difficulty: "basic", viralScore: 90 },
        { title: "동물병원에서 피부에 스카치테이프를 붙이는 이유 (피부 세포학 검사)", description: "테이프나 면봉으로 환부의 삼출물을 채취해 현미경으로 세균, 곰팡이, 염증 세포의 유무를 직접 눈으로 확인하는 기초 검사법.", tags: ["피부세포학","진단검사"], animal: "both", difficulty: "intermediate", viralScore: 85 },
        { title: "피부에 고름이 차는 세균성 모낭염(농피증) 완치 가이드", description: "면역력 저하나 긁은 상처를 통해 포도상구균 등이 침투해 발생하는 딱지와 농포의 4~6주 이상의 꾸준한 항생제 복용 필요성.", tags: ["농피증","모낭염"], animal: "dog", difficulty: "intermediate", viralScore: 89 },
        { title: "비듬이 우수수 떨어지거나 기름기가 떡지는 지루증(Seborrhea)", description: "피부 세포의 턴오버 주기가 비정상적으로 빨라져 건성 각질(비듬)이나 지성 피지(기름)가 과다 분비되는 지루증의 맞춤형 보습과 세정.", tags: ["지루증","비듬기름기"], animal: "both", difficulty: "advanced", viralScore: 86 },
        { title: "고양이 턱 밑에 생긴 까만 깨알, 고양이 턱 여드름(Feline Acne)", description: "플라스틱 식기 사용, 피지 분비 과다, 그루밍 부족 등으로 턱에 피지가 쌓여 모낭염으로 발전하는 턱 여드름의 소독과 사기그릇 교체.", tags: ["여드름","고양이턱드름"], animal: "cat", difficulty: "basic", viralScore: 93 },
        { title: "산책 후 발을 너무 자주 씻기면 발가락 사이 피부염(지간염)이 생긴다?", description: "습관적인 물 세척과 덜 말린 발가락 사이의 습한 환경이 곰팡이와 세균 증식을 유발하여 만성 지간염을 일으키는 최악의 습관.", tags: ["발가락사이피부염","지간염"], animal: "dog", difficulty: "basic", viralScore: 95 },
        { title: "구토나 설사 없이 피부병으로만 나타나는 음식 알레르기", description: "특정 육류 단백질에 대한 알레르기 반응이 위장관 트러블 대신 귀가 빨개지고 눈 주위가 붓는 피부 소양감으로 발현되는 기전.", tags: ["음식알레르기피부","식이알러지"], animal: "both", difficulty: "intermediate", viralScore: 91 },
        { title: "집먼지 진드기, 꽃가루 등 평생 안고 가야 할 환경 알레르기(아토피)", description: "완치가 불가능한 아토피성 피부염의 특성을 이해하고 보습제, 면역 치료, 주사제 등을 병행하며 증상을 통제하는 평생 관리 마인드.", tags: ["환경알레르기","아토피피부염"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "내 면역 세포가 내 피부를 공격하는 면역 매개성 피부 질환 (천포창)", description: "코, 발바닥, 귀 끝에 심한 궤양과 딱지가 앉으며 스테로이드와 면역 억제제 투여가 필수적인 무서운 자가면역 질환의 징후.", tags: ["면역매개피부질환","천포창"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "벼룩 한 마리가 전신 가려움증을? 벼룩 알레르기성 피부염(FAD)", description: "벼룩의 타액에 포함된 항원에 극도로 예민하게 반응하여 꼬리 윗부분과 등에 심한 탈모와 딱지를 유발하는 벼룩 알러지.", tags: ["벼룩알레르기","외부기생충"], animal: "dog", difficulty: "intermediate", viralScore: 87 },
        { title: "피부 조직의 일부를 떼어내는 피부 생검(Biopsy)이 필요한 순간", description: "치료에 전혀 반응하지 않는 만성 난치성 피부병이나 종양이 의심될 때 정확한 병명을 확진하기 위한 조직 검사의 필수성.", tags: ["피부생검","조직검사"], animal: "both", difficulty: "advanced", viralScore: 84 },
        { title: "강아지에게 사람 항히스타민제(지르텍 등)를 먹여도 효과가 있을까?", description: "개는 사람과 가려움증을 유발하는 화학 매개체가 달라 항히스타민제의 단독 효과가 떨어지며 수면 유도 등 부작용만 클 수 있음.", tags: ["항히스타민","약물효과"], animal: "dog", difficulty: "advanced", viralScore: 89 },
        { title: "사람 발무좀을 핥은 강아지, 피부 곰팡이증 전염의 위험성", description: "보호자의 무좀균(피부사상충)이 반려동물의 코나 발에 전염될 수 있으며 반대로 동물의 곰팡이가 사람에게 올 수 있는 인수공통 주의보.", tags: ["피부곰팡이","무좀전염"], animal: "both", difficulty: "basic", viralScore: 92 },
        { title: "스테로이드 연고 부작용, 피부가 얇아지고 혈관이 비치는 쿠싱 피부", description: "의사 처방 없이 오랫동안 스테로이드 연고를 오남용했을 때 콜라겐이 파괴되어 피부가 종잇장처럼 얇아지고 쉽게 찢어지는 부작용.", tags: ["자가면역피부","스테로이드부작용"], animal: "both", difficulty: "advanced", viralScore: 94 },
        { title: "플라스틱 식기나 특정 샴푸에 의한 접촉성 피부염", description: "배 부위나 턱, 발 등 특정 물건이 직접 닿는 부위에만 국소적으로 발생하는 붉은 발진의 원인 물질 찾기.", tags: ["접촉성피부염","자극성피부염"], animal: "both", difficulty: "basic", viralScore: 86 },
        { title: "피부가 까맣게 변하고 코끼리 가죽처럼 두꺼워지는 색소 침착(태선화)", description: "만성적인 염증과 가려움으로 오랫동안 피부를 긁었을 때 방어 기제로 멜라닌 색소가 침착되고 코끼리 피부처럼 변하는 후유증.", tags: ["색소침착","만성피부염"], animal: "both", difficulty: "intermediate", viralScore: 88 },
        { title: "건조한 겨울철 정전기와 각질을 잡는 피부 보습의 절대적 중요성", description: "표피의 세라마이드 층이 무너지면 알레르겐과 세균 침투가 쉬워지므로 펫 전용 세라마이드 스프레이나 스팟온 보습제를 활용한 장벽 강화.", tags: ["피부보습","피부장벽"], animal: "both", difficulty: "basic", viralScore: 91 },
        { title: "봄 가을 특정 시기에만 가려운 계절성 알레르기 패턴 분석", description: "일 년 중 특정 계절에만 피부병이 재발한다면 꽃가루나 풀 접촉을 의심하고 산책 후 물리적으로 항원을 씻어내는 닦아내기 처치.", tags: ["계절성알레르기","꽃가루알레르기"], animal: "both", difficulty: "intermediate", viralScore: 85 },
        { title: "건강한 피모를 만드는 핵심 영양소: 아연, 오메가3, 리놀레산", description: "사료에 부족하기 쉬운 필수 지방산과 미네랄이 털의 윤기를 더하고 피부 염증 세포의 활성을 억제하는 영양학적 효능.", tags: ["피부영양소","피모영양제"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "강아지와 고양이의 최적 목욕 빈도: 너무 잦은 목욕의 역효과", description: "각질층이 얇고 pH가 중성에 가까운 반려동물 피부를 사람처럼 자주 씻기면 천연 피지막이 파괴되어 오히려 피부병을 유발하는 이유.", tags: ["목욕빈도","피부건강"], animal: "both", difficulty: "basic", viralScore: 93 },
        { title: "불독, 퍼그 등 단두종의 치명적 약점, 안면 주름 피부염 완벽 관리", description: "코와 눈 사이 깊게 파인 주름에 눈물과 습기가 고여 악취와 곰팡이 감염이 일어나는 주름 피부염의 매일매일 건조와 소독법.", tags: ["단두종피부관리","주름피부염"], animal: "dog", difficulty: "intermediate", viralScore: 90 },
        { title: "피부에 난 종괴, 단순 사마귀(피지선종)와 비만세포종의 감별", description: "나이 든 개에서 흔한 양성 피지선종과, 만지면 염증 물질을 분비해 붓고 붉어지는 치명적인 악성 피부암(비만세포종)의 구별법.", tags: ["피부종양감별","비만세포종"], animal: "both", difficulty: "advanced", viralScore: 95 }
      ]
    },
    {
      id: "vet-eye-homecare",
      name: "안과/홈케어",
      icon: "👁️",
      topics: [
        { title: "붉은 눈물 자국(유루증)의 근본 원인과 사료 변경의 효과", description: "포르피린 색소에 의한 착색 원인(눈물샘 막힘, 속눈썹 찌름, 알레르기)과 수술적 개통 및 항산화 사료의 해결책.", tags: ["눈물자국","유루증"], animal: "dog", difficulty: "intermediate", viralScore: 94 },
        { title: "눈을 못 뜨고 깜빡이는 각막 궤양의 형광 염색 진단과 넥카라", description: "목욕 중 샴푸가 들어가거나 고양이 발톱에 긁혀 각막 상피가 벗겨진 극심한 통증과 즉각적인 안약 처치의 필요성.", tags: ["각막궤양","안과진료"], animal: "both", difficulty: "intermediate", viralScore: 91 },
        { title: "끈적한 눈곱과 충혈, 건성각결막염(안구건조증)의 평생 안약 관리", description: "면역 매개성으로 눈물샘이 파괴되어 눈물이 마르는 질환(KCS)의 눈물량(STT) 검사와 옵티뮨 연고 치료법.", tags: ["안구건조","눈곱"], animal: "dog", difficulty: "advanced", viralScore: 89 },
        { title: "눈앞머리에 붉은 혹이 튀어나오는 체리아이(제3안검 선 탈출증)", description: "코카스파니엘, 불독 등에서 눈 안쪽 제3안검의 눈물샘이 밖으로 돌출되는 증상과 이를 안으로 밀어 넣는 수술.", tags: ["체리아이","제3안검"], animal: "dog", difficulty: "intermediate", viralScore: 90 },
        { title: "하루 만에 실명할 수 있는 안압 상승의 공포, 녹내장 응급 처치", description: "안구 내 방수가 배출되지 않아 눈이 커지고 통증으로 식욕을 잃는 급성 녹내장의 안압 하강 안약과 수술 시기.", tags: ["녹내장","실명응급"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "백내장 수술 전 검사(ERG, 초음파)와 수술 후 안약 투여 지옥", description: "망막 기능이 정상인지 확인하는 예비 검사의 중요성과 인공수정체 삽입 수술 후 하루 수십 번 안약을 넣어야 하는 보호자의 홈케어.", tags: ["백내장수술","인공수정체"], animal: "dog", difficulty: "advanced", viralScore: 92 },
        { title: "눈이 튀어나올 듯 큰 단두종의 고질적인 안과 질환과 눈 보호", description: "시츄, 페키니즈의 눈이 외부 자극에 노출되어 궤양과 색소성 각막염이 잦은 구조적 문제와 산책 시 고글(도글스) 착용 팁.", tags: ["단두종눈관리","각막염"], animal: "dog", difficulty: "basic", viralScore: 88 },
        { title: "고양이 허스피스(칼리시) 바이러스에 의한 결막염과 L-라이신 영양제", description: "면역력이 떨어지면 재발하는 고양이 감기 바이러스성 결막염의 노란 눈곱 대처와 바이러스 증식을 억제하는 라이신 보조제 효능 논란.", tags: ["결막염","허스피스"], animal: "cat", difficulty: "intermediate", viralScore: 93 },
        { title: "밤눈이 어두워지다 완전히 실명하는 진행성 망막 위축증(PRA)", description: "푸들 등에서 유전적으로 발생하며 빛을 감지하는 망막 세포가 서서히 파괴되어 치료법이 없는 PRA의 대처와 유전자 검사.", tags: ["PRA","망막질환"], animal: "dog", difficulty: "advanced", viralScore: 95 },
        { title: "시력 보호와 백내장 지연을 위한 눈 영양제(루테인, 지아잔틴)의 진실", description: "항산화제가 망막 노화를 늦출 수는 있지만 이미 진행된 백내장을 녹이거나 치료할 수는 없는 눈 보조제의 올바른 기대 효과.", tags: ["눈영양소","백내장지연"], animal: "both", difficulty: "intermediate", viralScore: 87 },
        { title: "가정에서 정확하게 직장(항문) 체온 재는 방법과 정상 체온 범위", description: "전자 체온계 끝에 바셀린을 바르고 2cm 정도 삽입해 재는 가장 정확한 심부 체온 측정법과 38~39도 정상 범위 숙지하기.", tags: ["체온재기","기초검사"], animal: "both", difficulty: "basic", viralScore: 90 },
        { title: "뱉어내는 약, 거품 무는 고양이: 스트레스 제로 약 먹이기 필살기", description: "알약 주사기(필건) 사용법, 캡슐 씌우기, 간식(츄르/필포켓)에 숨기기 등 쓴 약을 먹일 때 보호자와 동물 모두 평화로운 투약 요령.", tags: ["약먹이기","투약요령"], animal: "both", difficulty: "basic", viralScore: 95 },
        { title: "찰과상 등 가벼운 피부 상처 소독과 강아지 전용 연고 바르기", description: "포비돈 요오드(빨간약)나 클로르헥시딘을 올바른 농도로 희석해 소독하고 동물이 핥지 않도록 처치하는 상처 응급 처치.", tags: ["상처소독","가벼운외상"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "한두 번의 무른 변과 설사 시 집에서 할 수 있는 단식과 유산균 처치", description: "구토나 활력 저하가 없는 단순 설사일 때 12~24시간 위장을 비우고 수분만 공급하며 경과를 지켜보는 홈케어 가이드.", tags: ["설사대처","위장휴식"], animal: "both", difficulty: "basic", viralScore: 92 },
        { title: "구토 후 물을 주면 다시 토하는 이유와 소량 급여의 원칙", description: "위 점막이 자극받은 상태에서 찬물이나 많은 양의 식사를 하면 반사적으로 구토가 재발하므로 얼음이나 소량의 물만 제공하는 법.", tags: ["구토후급여","소화기안정"], animal: "both", difficulty: "intermediate", viralScore: 94 },
        { title: "엘리자베스 칼라(넥카라) 거부감 줄이는 적응 훈련과 소재별 장단점", description: "플라스틱, 천, 튜브형 넥카라의 시야 확보와 환부 보호 능력을 비교하고 수술 전 미리 착용해 보며 스트레스를 줄이는 방법.", tags: ["엘리자베스칼라","수술후관리"], animal: "both", difficulty: "basic", viralScore: 89 },
        { title: "피가 나지 않게 검은 발톱 자르는 노하우와 혈관(Quick)의 이해", description: "투명 발톱과 달리 혈관이 안 보이는 검은 발톱을 조금씩 깎아내며 단면의 촉촉한 점을 확인해 피가 나기 전 멈추는 미세 컷팅 기술.", tags: ["발톱깎기","발톱혈관"], animal: "both", difficulty: "basic", viralScore: 93 },
        { title: "엉덩이를 끌고 다니는 똥꼬발랄? 항문낭 짜기의 정석", description: "항문 4시와 8시 방향에 위치한 냄새나는 액체 주머니(항문낭)가 파열되기 전에 목욕 시 부드럽게 짜내어 염증을 예방하는 스킬.", tags: ["항문낭","엉덩이끌기"], animal: "dog", difficulty: "basic", viralScore: 91 },
        { title: "면봉은 절대 금물! 수의사가 알려주는 안전한 귀 세정법", description: "귀 안에 세정액을 듬뿍 넣고 귀 밑부분(수직이도)을 마사지한 뒤 동물이 스스로 털어내게 하고 겉부분만 솜으로 닦아내는 올바른 방법.", tags: ["귀세정","면봉위험"], animal: "both", difficulty: "basic", viralScore: 94 },
        { title: "고양이 다이어트의 핵심, 소수점까지 확인하는 정밀 체중 측정", description: "사람 체중계에 안고 올라가는 부정확한 방법 대신 유아용/반려동물용 정밀 저울을 이용해 50g의 작은 증감까지 기록하는 다이어트 일기.", tags: ["체중측정","고양이다이어트"], animal: "cat", difficulty: "basic", viralScore: 86 },
        { title: "만성 신부전 보호자의 숙명, 집에서 놔주는 피하 수액(SubQ) 투여법", description: "나비바늘과 수액팩을 이용해 목덜미 피부 아래에 안전하게 수액을 주입하고 부종 흡수를 모니터링하는 신장병 말기 홈케어 스킬.", tags: ["피하수액","신부전홈케어"], animal: "both", difficulty: "advanced", viralScore: 98 },
        { title: "당뇨병 환자를 위한 귀끝 채혈과 가정용 혈당계 측정법", description: "알파트랙 등 동물 전용 혈당계를 이용해 식전/식후 혈당 곡선을 그리고 저혈당 쇼크(떨림, 발작) 응급 시 꿀이나 설탕물을 먹이는 대처.", tags: ["혈당측정","가정혈당"], animal: "both", difficulty: "advanced", viralScore: 95 },
        { title: "정확한 시간에 정확한 용량을, 인슐린 주사(피하주사) 놓는 법", description: "인슐린 병을 흔들지 않고 굴려서 섞는 방법부터 주사기 눈금 읽기, 그리고 식사 직후 피부를 꼬집어 안전하게 주사하는 일련의 과정.", tags: ["인슐린주사","당뇨치료"], animal: "both", difficulty: "advanced", viralScore: 96 },
        { title: "고양이 천식을 가라앉히는 에어로캣(흡입기) 사용 훈련", description: "기침과 호흡 곤란을 호소하는 천식 고양이에게 스테로이드 흡입기를 씌워 10회 이상 심호흡하게 만드는 긍정 강화 적응 훈련.", tags: ["흡입기사용","천식호흡기"], animal: "cat", difficulty: "advanced", viralScore: 94 },
        { title: "슬개골 수술 후 빠른 회복을 위한 홈 재활 운동(관절 가동 범위 운동)", description: "PROM(수동적 관절 운동)을 통해 굳어지는 관절을 부드럽게 풀어주고 근손실을 막아 정상적인 보행을 돕는 보호자의 물리 치료사 역할.", tags: ["재활운동","수술후재활"], animal: "dog", difficulty: "intermediate", viralScore: 91 },
        { title: "부기 빼는 냉찜질 vs 혈액 순환 돕는 온찜질, 상황별 적용", description: "수술 직후나 급성 염증(핫스팟)에는 얼음찜질로 부기를 가라앉히고, 만성 관절염이나 주사 부위 뭉침에는 따뜻한 찜질로 풀어주는 원리.", tags: ["냉찜질온찜질","물리치료"], animal: "both", difficulty: "basic", viralScore: 88 },
        { title: "상처 부위 핥지 못하게 감는 코반(자가점착 밴드)의 위험성", description: "털에 붙지 않아 편리한 코반 붕대를 너무 세게 감았을 때 발끝에 피가 통하지 않아 괴사(조직 썩음)가 발생할 수 있는 주의사항.", tags: ["반창고사용","압박붕대부작용"], animal: "both", difficulty: "intermediate", viralScore: 90 },
        { title: "식음 전폐한 환자를 살리는 식도/위 영양 튜브(Feeding Tube) 관리", description: "코나 목, 위로 삽입된 튜브를 통해 블렌더로 간 유동식을 막힘없이 주입하고 소독하여 생명을 유지하는 중환자 홈케어.", tags: ["영양튜브관리","유동식급여"], animal: "both", difficulty: "advanced", viralScore: 97 },
        { title: "심장병 환자의 호흡수를 낮추는 가정용 산소 발생기와 산소방 렌탈", description: "폐수종으로 호흡수(SRR)가 분당 30회를 넘을 때 응급조치로 농축된 산소를 공급해 응급실 가는 길의 생존율을 높이는 세팅.", tags: ["산소공급","심장병호흡곤란"], animal: "both", difficulty: "advanced", viralScore: 95 },
        { title: "고혈압 관리를 위한 꼬리/다리 도플러 가정 혈압 측정의 한계와 팁", description: "병원만 가면 혈압이 오르는 백의 고혈압을 배제하기 위해 집에서 안정된 상태로 여러 번 측정해 평균값을 구하는 혈압 모니터링.", tags: ["가정혈압측정","고혈압관리"], animal: "both", difficulty: "advanced", viralScore: 89 }
      ]
    }
  ]
};

const dir = path.join(__dirname, 'data');
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(path.join(dir, 'vet-300.json'), JSON.stringify(data, null, 2), 'utf8');

console.log('Successfully wrote data/vet-300.json with ' + data.subcategories.reduce((acc, sub) => acc + sub.topics.length, 0) + ' topics.');
