#!/usr/bin/env node
// Generate expanded content-db.json with 300 vet + 200 behavior topics + existing trends

const fs = require('fs');
const path = require('path');

// Load existing trends
const existing = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/content-db.json'), 'utf8'));
const trendCategory = existing.categories.find(c => c.id === 'trend');
const trendCategory2 = existing.categories.find(c => c.id === 'trends');

// Merge trend subcategories
const trendSubcats = [];
if (trendCategory) trendSubcats.push(...trendCategory.subcategories);
if (trendCategory2) {
  for (const sc of trendCategory2.subcategories) {
    if (sc.topics.length > 0 && !trendSubcats.find(s => s.id === sc.id)) {
      trendSubcats.push(sc);
    }
  }
}

// ============ 수의학 300 topics (10 subcategories x 30) ============
const vetSubcategories = [
  {
    id: "vet-nutrition", name: "영양학", icon: "🥗",
    topics: [
      { title: "강아지 필수 아미노산 10종 완벽 정리", description: "아르기닌, 히스티딘 등 강아지에게 필수적인 아미노산의 역할과 결핍 시 나타나는 증상을 상세히 알아봅니다.", tags: ["아미노산", "영양소", "필수영양"], animal: "dog", difficulty: "intermediate", viralScore: 72 },
      { title: "고양이 타우린 결핍의 위험성", description: "고양이에게 타우린이 부족하면 심장병과 실명까지 올 수 있습니다. 타우린 급여 가이드.", tags: ["타우린", "고양이영양", "심장"], animal: "cat", difficulty: "intermediate", viralScore: 85 },
      { title: "반려동물 오메가-3 지방산의 효과", description: "EPA와 DHA가 피부, 관절, 뇌 건강에 미치는 긍정적 효과와 올바른 보충 방법.", tags: ["오메가3", "지방산", "보충제"], animal: "both", difficulty: "basic", viralScore: 78 },
      { title: "강아지 칼슘 과잉 섭취의 부작용", description: "대형견 퍼피에게 칼슘을 과도하게 보충하면 골격 이상이 발생할 수 있습니다.", tags: ["칼슘", "대형견", "성장기"], animal: "dog", difficulty: "advanced", viralScore: 74 },
      { title: "비타민 A 과다 복용 시 독성 증상", description: "간 간식을 과도하게 급여하면 비타민A 중독이 발생합니다. 적정 급여량 안내.", tags: ["비타민A", "독성", "간간식"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "수분 섭취량 계산법 — 체중별 하루 권장량", description: "체중 1kg당 40~60ml가 기본. 건사료 급여 시 추가 수분이 필요한 이유.", tags: ["수분", "급여량", "건사료"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "생식(BARF) 다이어트의 장단점", description: "날고기 기반 생식 급여의 영양학적 이점과 세균 감염 위험성을 균형 있게 분석.", tags: ["생식", "BARF", "날고기"], animal: "dog", difficulty: "advanced", viralScore: 88 },
      { title: "곡물 프리 사료, 정말 좋을까?", description: "곡물 프리 사료와 DCM(확장성 심근병증) 연관성에 대한 FDA 조사 결과 정리.", tags: ["곡물프리", "DCM", "심장병"], animal: "dog", difficulty: "intermediate", viralScore: 91 },
      { title: "고양이 습식 vs 건식 사료 영양 비교", description: "수분 함량, 단백질 밀도, 칼로리 차이를 기준으로 습식과 건식의 영양학적 차이 비교.", tags: ["습식", "건식", "사료비교"], animal: "cat", difficulty: "basic", viralScore: 80 },
      { title: "비타민 D 결핍과 뼈 건강의 관계", description: "반려동물은 햇빛으로 비타민D를 합성하지 못합니다. 사료 내 적정 함량 확인법.", tags: ["비타민D", "뼈건강", "영양결핍"], animal: "both", difficulty: "intermediate", viralScore: 70 },
      { title: "철분 부족으로 인한 빈혈 증상과 대처", description: "잇몸 창백, 무기력 등 철분 결핍성 빈혈의 초기 증상과 식이 보충 방법.", tags: ["철분", "빈혈", "영양결핍"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "아연 결핍이 피부에 미치는 영향", description: "시베리안 허스키 등 특정 견종에서 흔한 아연 반응성 피부질환의 원인과 치료.", tags: ["아연", "피부", "견종별"], animal: "dog", difficulty: "advanced", viralScore: 69 },
      { title: "프로바이오틱스가 장건강에 미치는 효과", description: "유산균 보충이 반려동물의 소화기 건강, 면역력 강화에 미치는 과학적 근거.", tags: ["프로바이오틱스", "장건강", "유산균"], animal: "both", difficulty: "basic", viralScore: 83 },
      { title: "글루코사민과 콘드로이틴의 관절 보호 효과", description: "관절 보조제의 실제 효과에 대한 수의학 연구 결과와 권장 용량 정리.", tags: ["글루코사민", "관절", "보조제"], animal: "both", difficulty: "intermediate", viralScore: 77 },
      { title: "강아지에게 절대 먹이면 안 되는 음식 15가지", description: "포도, 양파, 자일리톨, 마카다미아 등 치명적인 독성 식품 목록과 응급 대처법.", tags: ["독성음식", "금지식품", "응급"], animal: "dog", difficulty: "basic", viralScore: 96 },
      { title: "고양이에게 위험한 식물과 음식", description: "백합, 양파, 마늘, 카페인 등 고양이에게 치명적인 물질 완벽 정리.", tags: ["독성식물", "금지식품", "고양이"], animal: "cat", difficulty: "basic", viralScore: 93 },
      { title: "임신한 반려동물의 영양 관리", description: "임신기와 수유기에 필요한 칼로리, 단백질, 칼슘 증가량 가이드.", tags: ["임신", "수유", "영양관리"], animal: "both", difficulty: "advanced", viralScore: 71 },
      { title: "퍼피 성장기 영양소 배분 가이드", description: "생후 2개월~12개월 퍼피의 체중별 적정 칼로리와 영양소 비율 안내.", tags: ["퍼피", "성장기", "칼로리"], animal: "dog", difficulty: "intermediate", viralScore: 79 },
      { title: "키튼 전용 사료가 필요한 이유", description: "성묘 사료와 키튼 사료의 단백질·지방 비율 차이와 성장기 고양이 영양 요구량.", tags: ["키튼", "성장기", "고양이사료"], animal: "cat", difficulty: "basic", viralScore: 75 },
      { title: "시니어 반려동물 칼로리 조절법", description: "노령 동물의 기초대사량 감소에 따른 칼로리 20~30% 감량 가이드.", tags: ["시니어", "칼로리", "다이어트"], animal: "both", difficulty: "basic", viralScore: 76 },
      { title: "식이섬유의 역할 — 변비와 설사 모두 해결", description: "수용성·불용성 식이섬유의 차이와 소화기 문제별 적합한 섬유 선택.", tags: ["식이섬유", "소화", "변비"], animal: "both", difficulty: "intermediate", viralScore: 72 },
      { title: "코코넛 오일, 반려동물에게 괜찮을까?", description: "중쇄지방산(MCT)의 효능과 과다 급여 시 설사, 췌장염 위험에 대한 분석.", tags: ["코코넛오일", "MCT", "트렌드"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "강아지 간식 칼로리 — 하루 총 섭취량의 10% 룰", description: "간식 과다 급여로 인한 비만을 예방하는 10% 룰과 저칼로리 간식 추천.", tags: ["간식", "칼로리", "비만예방"], animal: "dog", difficulty: "basic", viralScore: 84 },
      { title: "고양이 음수량 늘리는 5가지 방법", description: "흐르는 물 급수기, 습식 혼합, 국물 토핑 등 고양이 수분 섭취 증가 꿀팁.", tags: ["음수량", "수분", "고양이"], animal: "cat", difficulty: "basic", viralScore: 87 },
      { title: "L-카르니틴의 체지방 감소 효과", description: "비만 반려동물의 체중 관리에 L-카르니틴 보충이 실제로 도움이 되는지 연구 결과 분석.", tags: ["L카르니틴", "비만", "체중관리"], animal: "both", difficulty: "advanced", viralScore: 68 },
      { title: "단백질 알레르기와 새로운 단백원 선택", description: "닭고기 알레르기 시 사슴고기, 캥거루, 곤충 단백 등 노벨 프로틴 사료 가이드.", tags: ["알레르기", "단백원", "노벨프로틴"], animal: "both", difficulty: "intermediate", viralScore: 79 },
      { title: "반려동물 영양제, 정말 필요할까?", description: "균형 잡힌 사료를 급여 중이라면 추가 영양제가 불필요한 경우가 많습니다.", tags: ["영양제", "보충제", "과잉"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "BCS(체형지수)로 비만도 자가 진단하기", description: "갈비뼈 촉진, 허리 라인 관찰 등 9단계 체형지수 평가법 완벽 가이드.", tags: ["BCS", "비만도", "체형평가"], animal: "both", difficulty: "basic", viralScore: 85 },
      { title: "구리 축적 간질환과 식이 관리", description: "베들링턴 테리어 등 구리 대사 장애 견종의 저구리 식이 관리 방법.", tags: ["구리", "간질환", "견종별"], animal: "dog", difficulty: "advanced", viralScore: 65 },
      { title: "수제 간식 만들기 — 안전한 재료와 레시피", description: "닭가슴살 저키, 고구마칩, 단호박 쿠키 등 집에서 만드는 건강 간식 레시피.", tags: ["수제간식", "레시피", "건강간식"], animal: "both", difficulty: "basic", viralScore: 90 },
    ]
  },
  {
    id: "vet-feed", name: "사료학", icon: "🍖",
    topics: [
      { title: "사료 라벨 읽는 법 — 성분표 완전 해독", description: "조단백, 조지방, 조섬유, 조회분의 의미와 원재료 순서가 알려주는 정보.", tags: ["라벨", "성분표", "사료선택"], animal: "both", difficulty: "basic", viralScore: 88 },
      { title: "AAFCO 기준이란? — 사료 영양 적합성 인증", description: "미국사료관리협회의 영양 기준과 급여시험 통과 사료를 구별하는 방법.", tags: ["AAFCO", "인증", "영양기준"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "사료 등급 분류 — 홀리스틱부터 일반까지", description: "홀리스틱, 슈퍼프리미엄, 프리미엄, 일반 등급별 원재료와 가격 차이 비교.", tags: ["사료등급", "품질", "가격비교"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "리콜 이력 확인하는 방법", description: "FDA 리콜 데이터베이스와 국내 리콜 정보를 확인하는 실용적 방법 안내.", tags: ["리콜", "안전성", "FDA"], animal: "both", difficulty: "basic", viralScore: 86 },
      { title: "강아지 사료 브랜드 TOP 10 비교 분석", description: "로얄캐닌, 오리젠, 아카나, 뉴트로 등 인기 브랜드의 장단점 비교.", tags: ["브랜드", "비교", "추천"], animal: "dog", difficulty: "basic", viralScore: 92 },
      { title: "고양이 사료 브랜드 TOP 10 비교", description: "로얄캐닌, 고우, 지위픽, 내추럴발란스 등 고양이 사료 브랜드 심층 비교.", tags: ["브랜드", "고양이사료", "추천"], animal: "cat", difficulty: "basic", viralScore: 90 },
      { title: "건사료 보관법 — 산패 방지 가이드", description: "개봉 후 산패를 막는 밀봉 용기 사용법과 적정 보관 온도, 기간 안내.", tags: ["보관법", "산패", "식품안전"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "습식 사료 선택 시 체크포인트", description: "수분 함량, 첨가물, 주원료 비율 등 습식 캔 선택 시 확인해야 할 5가지.", tags: ["습식사료", "캔사료", "체크리스트"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "에어 드라이 vs 프리즈 드라이 차이점", description: "제조 공정별 영양소 보존율 차이와 각 타입의 장단점 비교 분석.", tags: ["에어드라이", "프리즈드라이", "제조공정"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "사료 전환 시 주의사항 — 7일 전환법", description: "급격한 사료 변경 시 발생하는 소화 문제를 예방하는 단계적 전환 방법.", tags: ["사료전환", "소화", "급여법"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "부산물(by-product)의 진실", description: "사료 원재료의 '부산물'이 반드시 나쁜 것은 아닌 이유와 올바른 해석.", tags: ["부산물", "원재료", "오해"], animal: "both", difficulty: "intermediate", viralScore: 79 },
      { title: "가수분해 단백질 사료의 원리", description: "알레르기 반응을 줄이기 위해 단백질을 분해하는 가수분해 공정의 과학적 원리.", tags: ["가수분해", "알레르기", "특수사료"], animal: "both", difficulty: "advanced", viralScore: 71 },
      { title: "곤충 단백 사료 — 미래의 지속 가능한 선택", description: "동애등에 유충 기반 사료의 영양가와 환경적 이점, 수용성 분석.", tags: ["곤충단백", "지속가능", "미래사료"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "국내 사료 vs 수입 사료 비교", description: "국내 제조 사료와 수입 사료의 규제, 품질, 가성비 차이 분석.", tags: ["국산", "수입", "비교분석"], animal: "both", difficulty: "basic", viralScore: 83 },
      { title: "사료에 들어가는 방부제와 항산화제", description: "BHA, BHT, 에톡시퀸 vs 토코페롤, 로즈마리 추출물 등 방부제 안전성 비교.", tags: ["방부제", "항산화제", "첨가물"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "한정 원재료(LID) 사료란?", description: "식이 민감성이 있는 반려동물을 위한 제한 원재료 사료의 개념과 선택법.", tags: ["LID", "민감성", "알레르기"], animal: "both", difficulty: "intermediate", viralScore: 72 },
      { title: "사료 급여량 계산기 — 체중·활동량 기반", description: "RER과 DER을 이용한 정확한 일일 사료 급여량 계산 방법.", tags: ["급여량", "칼로리계산", "RER"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "오가닉 사료의 기준과 인증 마크", description: "유기농 인증을 받으려면 어떤 기준을 충족해야 하는지, 인증 마크 해석법.", tags: ["유기농", "오가닉", "인증"], animal: "both", difficulty: "intermediate", viralScore: 70 },
      { title: "단백질 함량 높은 사료가 무조건 좋을까?", description: "고단백 사료의 장점과 신장 질환, 과체중 동물에게 미치는 부정적 영향.", tags: ["고단백", "신장", "사료선택"], animal: "both", difficulty: "intermediate", viralScore: 81 },
      { title: "사료 리뷰 사이트 활용법", description: "Dog Food Advisor, 국내 커뮤니티 리뷰를 현명하게 참고하는 방법.", tags: ["리뷰", "정보검색", "사료평가"], animal: "both", difficulty: "basic", viralScore: 73 },
      { title: "채식 사료, 강아지에게 적합한가?", description: "강아지의 잡식성 특성과 채식 사료의 영양 완전성에 대한 논쟁 정리.", tags: ["채식사료", "비건", "논쟁"], animal: "dog", difficulty: "advanced", viralScore: 85 },
      { title: "생식 사료(냉동 생식) 안전하게 급여하기", description: "살모넬라, 리스테리아 위험을 줄이는 생식 사료 취급 및 위생 관리 가이드.", tags: ["생식사료", "위생", "세균"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "토핑 급여의 올바른 방법", description: "건사료에 습식, 육류, 채소를 토핑할 때 영양 불균형을 피하는 요령.", tags: ["토핑", "혼합급여", "영양균형"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "자동 급식기 선택 가이드", description: "습식 사료용, 건식용 자동 급식기의 기능별 비교와 추천 제품.", tags: ["자동급식기", "제품추천", "편의용품"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "사료 알레르기 검사 — 제거식이법", description: "8주간의 제거식이 시험을 통해 알레르기 원인 성분을 찾는 정석적 방법.", tags: ["알레르기검사", "제거식이", "진단"], animal: "both", difficulty: "advanced", viralScore: 74 },
      { title: "퍼피용 vs 올라이프 사료 차이", description: "전연령 사료와 생애주기별 사료의 영양 설계 차이와 선택 기준.", tags: ["퍼피", "올라이프", "생애주기"], animal: "both", difficulty: "basic", viralScore: 72 },
      { title: "대형견 전용 사료가 필요한 이유", description: "대형견의 성장 속도에 맞춘 칼슘·인 비율과 관절 보호 성분의 중요성.", tags: ["대형견", "특수사료", "관절"], animal: "dog", difficulty: "intermediate", viralScore: 75 },
      { title: "고양이 사료 기호성 높이는 꿀팁", description: "사료 거부하는 고양이를 위한 데우기, 토핑, 질감 변경 등 실전 팁.", tags: ["기호성", "사료거부", "고양이"], animal: "cat", difficulty: "basic", viralScore: 86 },
      { title: "사료 원재료 원산지 확인의 중요성", description: "중국산 원재료 논란과 원산지 표기 의무, 투명한 브랜드 선별법.", tags: ["원산지", "안전성", "투명성"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "사료 가격대별 추천 — 가성비 사료 BEST", description: "월 5만원 이하, 5~10만원, 10만원 이상 가격대별 추천 사료 리스트.", tags: ["가성비", "가격비교", "추천"], animal: "both", difficulty: "basic", viralScore: 89 },
    ]
  },
  {
    id: "vet-disease", name: "질병백과", icon: "🏥",
    topics: [
      { title: "강아지 슬개골 탈구 — 등급별 증상과 치료", description: "소형견에서 흔한 슬개골 탈구의 1~4등급 분류와 수술 적응증 안내.", tags: ["슬개골탈구", "소형견", "정형외과"], animal: "dog", difficulty: "intermediate", viralScore: 92 },
      { title: "고양이 만성 신부전 — 초기 발견이 핵심", description: "10세 이상 고양이의 30%가 걸리는 만성 신부전의 초기 증상과 관리법.", tags: ["신부전", "만성질환", "시니어"], animal: "cat", difficulty: "intermediate", viralScore: 90 },
      { title: "강아지 디스크(IVDD) 완벽 가이드", description: "추간판 탈출증의 원인, 증상 단계, 보존치료 vs 수술 판단 기준.", tags: ["디스크", "IVDD", "척추"], animal: "dog", difficulty: "advanced", viralScore: 87 },
      { title: "고양이 하부요로계 질환(FLUTD) 총정리", description: "혈뇨, 빈뇨, 부적절한 배뇨 등 FLUTD 증상과 스트레스 관리의 중요성.", tags: ["FLUTD", "비뇨기", "스트레스"], animal: "cat", difficulty: "intermediate", viralScore: 85 },
      { title: "반려동물 당뇨병 — 인슐린 관리 가이드", description: "당뇨 진단 후 가정에서의 인슐린 주사, 혈당 모니터링, 식이 조절 방법.", tags: ["당뇨", "인슐린", "만성질환"], animal: "both", difficulty: "advanced", viralScore: 79 },
      { title: "강아지 심장사상충 — 예방이 치료보다 쉽다", description: "심장사상충 감염 경로, 증상, 예방약 종류와 투여 스케줄 정리.", tags: ["심장사상충", "예방", "기생충"], animal: "dog", difficulty: "basic", viralScore: 91 },
      { title: "고양이 갑상선 기능항진증", description: "중노령 고양이에서 흔한 갑상선 기능항진증의 증상, 진단, 치료 옵션.", tags: ["갑상선", "호르몬", "시니어"], animal: "cat", difficulty: "intermediate", viralScore: 76 },
      { title: "강아지 파보바이러스 — 치사율과 치료", description: "파보바이러스의 감염 경로, 혈변·구토 증상, 입원 치료의 중요성.", tags: ["파보", "바이러스", "전염병"], animal: "dog", difficulty: "intermediate", viralScore: 88 },
      { title: "고양이 전염성 복막염(FIP) 신약 치료", description: "한때 불치병이었던 FIP의 GS-441524 치료제 등장과 치료 프로토콜.", tags: ["FIP", "전염병", "신약"], animal: "cat", difficulty: "advanced", viralScore: 93 },
      { title: "쿠싱 증후군 — 물 많이 마시는 강아지", description: "부신피질 호르몬 과다 분비로 인한 쿠싱의 증상, 진단, 약물치료.", tags: ["쿠싱", "호르몬", "부신"], animal: "dog", difficulty: "advanced", viralScore: 74 },
      { title: "반려동물 암의 초기 신호 10가지", description: "비정상 종괴, 체중 감소, 식욕 부진 등 조기 발견을 위한 체크리스트.", tags: ["암", "종양", "조기발견"], animal: "both", difficulty: "intermediate", viralScore: 94 },
      { title: "강아지 외이염 — 원인과 예방법", description: "세균, 효모, 알레르기로 인한 외이염의 증상과 귀 세정 관리법.", tags: ["외이염", "귀감염", "예방"], animal: "dog", difficulty: "basic", viralScore: 82 },
      { title: "고양이 구내염 — 통증 관리가 핵심", description: "심한 구내염으로 식사가 어려운 고양이의 발치 치료와 통증 관리.", tags: ["구내염", "발치", "통증"], animal: "cat", difficulty: "intermediate", viralScore: 78 },
      { title: "반려동물 췌장염 — 급성 vs 만성", description: "고지방 간식 급여 후 발생하는 췌장염의 증상, 금식 치료, 재발 예방.", tags: ["췌장염", "소화기", "금식"], animal: "both", difficulty: "intermediate", viralScore: 83 },
      { title: "강아지 관절염 — 체중 관리와 운동 조절", description: "퇴행성 관절염의 비수술적 관리법과 통증 완화를 위한 약물 치료.", tags: ["관절염", "통증", "노령"], animal: "dog", difficulty: "intermediate", viralScore: 80 },
      { title: "고양이 천식 — 호흡 곤란 응급 대처", description: "고양이 천식의 원인, 증상, 흡입기 사용법과 환경 관리.", tags: ["천식", "호흡기", "응급"], animal: "cat", difficulty: "intermediate", viralScore: 77 },
      { title: "강아지 간질(뇌전증) 관리 가이드", description: "발작 시 대처법, 항경련제 복용, 발작 일지 작성의 중요성.", tags: ["뇌전증", "발작", "신경과"], animal: "dog", difficulty: "advanced", viralScore: 81 },
      { title: "고양이 변비 — 거대결장까지 진행되기 전에", description: "만성 변비의 원인, 식이 조절, 약물 치료, 거대결장 수술까지의 과정.", tags: ["변비", "거대결장", "소화기"], animal: "cat", difficulty: "intermediate", viralScore: 75 },
      { title: "강아지 알레르기 — 식이성 vs 환경성 구별법", description: "가려움의 원인이 음식인지 환경인지 감별하는 진단 과정과 치료 전략.", tags: ["알레르기", "가려움", "진단"], animal: "dog", difficulty: "intermediate", viralScore: 86 },
      { title: "반려동물 요로결석 — 종류별 관리법", description: "스트루바이트, 옥살레이트 등 결석 종류에 따른 식이·수술 치료 비교.", tags: ["요로결석", "비뇨기", "식이관리"], animal: "both", difficulty: "advanced", viralScore: 78 },
      { title: "강아지 켄넬코프(기관지염)", description: "전염성 기관지염의 증상, 전파 경로, 예방접종과 격리의 중요성.", tags: ["켄넬코프", "기관지염", "전염"], animal: "dog", difficulty: "basic", viralScore: 76 },
      { title: "고양이 결막염 — 허피스 바이러스 감염", description: "고양이 허피스 바이러스로 인한 결막염의 치료와 재발 관리.", tags: ["결막염", "허피스", "눈감염"], animal: "cat", difficulty: "intermediate", viralScore: 73 },
      { title: "강아지 자궁축농증 — 중성화의 중요성", description: "미중성화 암컷에서 발생하는 자궁축농증의 응급성과 수술 치료.", tags: ["자궁축농증", "중성화", "응급수술"], animal: "dog", difficulty: "intermediate", viralScore: 84 },
      { title: "반려동물 림프종 — 항암치료 가이드", description: "림프종 진단 후 항암 프로토콜, 부작용 관리, 생존율에 대한 현실적 안내.", tags: ["림프종", "항암", "종양학"], animal: "both", difficulty: "advanced", viralScore: 82 },
      { title: "강아지 고관절 이형성증(HD)", description: "대형견에서 흔한 고관절 이형성증의 유전적 요인과 수술적 치료법.", tags: ["고관절", "이형성증", "대형견"], animal: "dog", difficulty: "advanced", viralScore: 77 },
      { title: "고양이 비대성 심근병증(HCM)", description: "고양이 심장병 중 가장 흔한 HCM의 초음파 진단과 약물 관리.", tags: ["HCM", "심장병", "초음파"], animal: "cat", difficulty: "advanced", viralScore: 80 },
      { title: "강아지 아디슨병(부신피질기능저하증)", description: "구토, 탈수, 저혈압을 일으키는 아디슨병의 진단과 평생 관리.", tags: ["아디슨", "호르몬", "부신"], animal: "dog", difficulty: "advanced", viralScore: 70 },
      { title: "반려동물 비만 관련 질환 총정리", description: "당뇨, 관절질환, 간지질증 등 비만이 유발하는 이차 질환 목록과 예방법.", tags: ["비만", "합병증", "체중관리"], animal: "both", difficulty: "basic", viralScore: 87 },
      { title: "강아지 십자인대 파열 — 수술과 재활", description: "전방십자인대 파열의 진단, TPLO 수술, 재활 운동 프로그램 안내.", tags: ["십자인대", "수술", "재활"], animal: "dog", difficulty: "advanced", viralScore: 79 },
      { title: "고양이 고혈압 — 눈과 신장을 지켜라", description: "고혈압이 망막 박리와 신장 손상을 일으키는 기전과 약물 치료.", tags: ["고혈압", "신장", "눈"], animal: "cat", difficulty: "advanced", viralScore: 74 },
    ]
  },
  {
    id: "vet-prescription", name: "처방식/치료식", icon: "💊",
    topics: [
      { title: "신장 질환 처방식 — 저단백·저인 식이의 원리", description: "만성 신부전 환자에게 단백질과 인을 제한하는 과학적 근거와 처방식 종류.", tags: ["신장", "처방식", "저단백"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "요로결석 용해 처방식 — 스트루바이트 vs 옥살레이트", description: "스트루바이트는 식이로 용해 가능하지만 옥살레이트는 불가능한 이유.", tags: ["요로결석", "처방식", "용해"], animal: "both", difficulty: "advanced", viralScore: 75 },
      { title: "간질환 처방식의 영양 설계", description: "간 기능 저하 시 단백질 질과 양을 조절하는 처방식의 핵심 원리.", tags: ["간질환", "처방식", "단백질"], animal: "both", difficulty: "advanced", viralScore: 68 },
      { title: "당뇨 관리 처방식 — 식이섬유와 복합탄수화물", description: "당뇨 환자의 혈당 안정을 위한 고섬유, 저혈당지수 처방식 가이드.", tags: ["당뇨", "처방식", "혈당"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "체중 감량 처방식 — 사타이어티 포뮬러", description: "포만감을 유지하면서 칼로리를 줄이는 비만 관리 처방식의 작용 원리.", tags: ["비만", "처방식", "다이어트"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "소화기 질환 처방식 — 고소화성 사료", description: "IBD, 만성 설사, 구토 환자를 위한 고소화성 저잔사 처방식 안내.", tags: ["소화기", "IBD", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "심장병 처방식 — 나트륨 제한의 중요성", description: "심부전 환자의 체액 저류를 줄이는 저나트륨 처방식과 타우린 보충.", tags: ["심장병", "나트륨", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 72 },
      { title: "관절 질환 처방식 — 기능성 성분 포함", description: "글루코사민, EPA, 콘드로이틴이 포함된 관절 지원 처방식의 효과.", tags: ["관절", "처방식", "기능성"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "피부 질환 처방식 — 오메가 강화 포뮬러", description: "아토피, 지루성 피부염 환자를 위한 오메가-3/6 강화 처방식 가이드.", tags: ["피부", "오메가", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 77 },
      { title: "췌장염 처방식 — 초저지방 식이", description: "급성 췌장염 회복 후 재발 방지를 위한 지방 8% 이하 처방식.", tags: ["췌장염", "저지방", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 79 },
      { title: "갑상선 질환 처방식 — 요오드 제한식", description: "고양이 갑상선 기능항진증에서 요오드 제한 처방식(y/d)의 작용 기전.", tags: ["갑상선", "요오드", "처방식"], animal: "cat", difficulty: "advanced", viralScore: 69 },
      { title: "알레르기 처방식 — 가수분해 vs 노벨 프로틴", description: "가수분해 단백질 사료와 새로운 단백원 사료 중 어떤 것을 선택할지 가이드.", tags: ["알레르기", "가수분해", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "구강 건강 처방식 — 치석 억제 기능", description: "크로켓 크기와 질감으로 기계적 치석 제거를 돕는 구강 처방식.", tags: ["치석", "구강", "처방식"], animal: "both", difficulty: "basic", viralScore: 71 },
      { title: "스트레스 관리 처방식 — 항불안 성분 포함", description: "L-트립토판, 카소제핀 등 스트레스 완화 성분이 포함된 특수 사료.", tags: ["스트레스", "항불안", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 75 },
      { title: "수술 후 회복기 처방식", description: "고칼로리·고단백으로 수술 후 조직 회복을 지원하는 회복기 사료.", tags: ["수술후", "회복", "처방식"], animal: "both", difficulty: "basic", viralScore: 70 },
      { title: "인지 기능 저하 처방식 — 시니어 브레인 케어", description: "항산화제, MCT, DHA가 포함된 인지 기능 지원 시니어 처방식.", tags: ["인지기능", "시니어", "브레인"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "처방식 급여 시 주의사항", description: "수의사 처방 없이 임의로 처방식을 급여하면 안 되는 이유와 부작용.", tags: ["처방식주의", "수의사", "안전"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "처방식과 일반 사료 혼합 급여 가능할까?", description: "처방식의 치료 효과를 떨어뜨리는 혼합 급여의 위험성 안내.", tags: ["혼합급여", "처방식", "효과감소"], animal: "both", difficulty: "basic", viralScore: 78 },
      { title: "고양이 특발성 방광염(FIC) 처방식", description: "스트레스 관리와 수분 섭취를 동시에 해결하는 FIC 전용 처방식.", tags: ["FIC", "방광염", "고양이"], animal: "cat", difficulty: "intermediate", viralScore: 76 },
      { title: "강아지 IBD 관리를 위한 장기 식이 전략", description: "염증성 장질환 환자의 장기적인 식이 관리와 처방식 선택 기준.", tags: ["IBD", "장기관리", "식이"], animal: "dog", difficulty: "advanced", viralScore: 72 },
      { title: "처방식 브랜드 비교 — 로얄캐닌 vs 힐스 vs 퓨리나", description: "3대 처방식 브랜드의 라인업, 가격, 연구 기반 비교 분석.", tags: ["브랜드비교", "처방식", "추천"], animal: "both", difficulty: "basic", viralScore: 86 },
      { title: "영양 불균형 교정 처방식", description: "수제식이나 잘못된 급여로 인한 영양 불균형을 교정하는 처방식 사용.", tags: ["영양불균형", "교정", "처방식"], animal: "both", difficulty: "intermediate", viralScore: 67 },
      { title: "고섬유 처방식 — 당뇨와 비만 동시 관리", description: "식이섬유가 혈당 조절과 포만감 유지에 동시에 기여하는 원리.", tags: ["고섬유", "당뇨", "비만"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "처방식의 적정 급여 기간", description: "질환별로 처방식을 얼마나 오래 급여해야 하는지에 대한 수의학 가이드.", tags: ["급여기간", "처방식", "관리"], animal: "both", difficulty: "basic", viralScore: 69 },
      { title: "식욕 없는 환자를 위한 처방식 급여 팁", description: "데우기, 소량 빈번 급여, 강제 급여 등 식욕부진 환자 급여 전략.", tags: ["식욕부진", "급여팁", "환자관리"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "소화기 민감 고양이를 위한 처방식 TOP 5", description: "구토, 설사가 잦은 고양이에게 적합한 처방식 5종 비교 리뷰.", tags: ["소화기", "고양이", "추천"], animal: "cat", difficulty: "basic", viralScore: 83 },
      { title: "저알레르기 처방식의 한계", description: "가수분해 사료도 100% 알레르기 차단이 불가능한 이유와 대안.", tags: ["알레르기", "한계", "대안"], animal: "both", difficulty: "advanced", viralScore: 71 },
      { title: "처방식 구매 채널 — 동물병원 vs 온라인", description: "처방식 구매 경로별 장단점과 정품 확인 방법 안내.", tags: ["구매", "정품", "채널"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "홈메이드 처방식 레시피의 위험성", description: "인터넷 처방식 레시피의 93%가 영양 불균형이라는 연구 결과.", tags: ["홈메이드", "영양불균형", "위험"], animal: "both", difficulty: "intermediate", viralScore: 84 },
      { title: "처방식 거부 시 대안 전략", description: "처방식을 거부하는 반려동물을 위한 점진적 적응과 대안 제품 탐색.", tags: ["사료거부", "대안", "적응"], animal: "both", difficulty: "basic", viralScore: 76 },
    ]
  },
  {
    id: "vet-preventive", name: "예방의학", icon: "🛡️",
    topics: [
      { title: "강아지 예방접종 스케줄 완벽 정리", description: "DHPPL, 코로나, 켄넬코프, 광견병 등 필수·선택 백신 접종 시기.", tags: ["예방접종", "백신", "스케줄"], animal: "dog", difficulty: "basic", viralScore: 93 },
      { title: "고양이 예방접종 가이드", description: "FVRCP, FeLV, 광견병 등 고양이 필수 백신과 실내묘 접종 여부.", tags: ["예방접종", "고양이", "백신"], animal: "cat", difficulty: "basic", viralScore: 89 },
      { title: "심장사상충 예방약 종류와 비교", description: "경구, 바르는 타입, 주사형 심장사상충 예방약의 효과와 부작용 비교.", tags: ["심장사상충", "예방약", "비교"], animal: "both", difficulty: "basic", viralScore: 87 },
      { title: "내부 기생충 구충 — 회충, 촌충, 편충", description: "계절별 구충 스케줄과 기생충별 감염 증상, 구충제 선택 가이드.", tags: ["구충", "기생충", "내부기생충"], animal: "both", difficulty: "basic", viralScore: 80 },
      { title: "외부 기생충 예방 — 진드기, 벼룩, 모낭충", description: "넥스가드, 브라벡토, 프론트라인 등 외부 기생충 예방제 비교.", tags: ["진드기", "벼룩", "외부기생충"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "건강검진 주기 — 연령별 권장 검사 항목", description: "퍼피, 성견, 시니어별 연 1~2회 건강검진 시 필요한 검사 항목.", tags: ["건강검진", "예방", "정기검사"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "중성화 수술의 장단점", description: "조기 중성화의 건강 이점과 대형견에서의 잠재적 부작용에 대한 논쟁.", tags: ["중성화", "수술", "논쟁"], animal: "both", difficulty: "intermediate", viralScore: 90 },
      { title: "마이크로칩 등록의 중요성", description: "동물등록법에 따른 의무 등록과 미등록 시 과태료, 분실 시 찾는 방법.", tags: ["마이크로칩", "동물등록", "법률"], animal: "both", difficulty: "basic", viralScore: 78 },
      { title: "강아지 치아 관리 — 칫솔질 습관화하기", description: "매일 칫솔질의 중요성과 반려견이 거부하지 않는 단계적 적응법.", tags: ["치아관리", "칫솔질", "구강"], animal: "dog", difficulty: "basic", viralScore: 83 },
      { title: "고양이 치아 관리 — 치석 예방 간식과 장난감", description: "칫솔질이 어려운 고양이를 위한 대안적 구강 관리 방법.", tags: ["치아관리", "고양이", "치석"], animal: "cat", difficulty: "basic", viralScore: 79 },
      { title: "발톱 깎기 안전 가이드", description: "퀵(혈관)을 피해 안전하게 발톱을 깎는 방법과 출혈 시 지혈법.", tags: ["발톱", "그루밍", "안전"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "귀 세정 올바른 방법", description: "귀 세정액 사용법과 과도한 세정이 오히려 해로운 이유.", tags: ["귀세정", "그루밍", "외이염예방"], animal: "both", difficulty: "basic", viralScore: 76 },
      { title: "산책 후 진드기 체크 루틴", description: "산책 후 반드시 확인해야 할 진드기 호발 부위와 안전 제거법.", tags: ["진드기", "산책", "체크리스트"], animal: "dog", difficulty: "basic", viralScore: 85 },
      { title: "계절별 건강 관리 체크리스트", description: "봄(알레르기), 여름(열사병), 가을(구충), 겨울(관절) 계절별 관리.", tags: ["계절별", "체크리스트", "건강관리"], animal: "both", difficulty: "basic", viralScore: 80 },
      { title: "반려동물 혈액형과 수혈", description: "강아지 DEA 1.1, 고양이 A/B/AB형 등 혈액형 사전 검사의 중요성.", tags: ["혈액형", "수혈", "응급"], animal: "both", difficulty: "advanced", viralScore: 72 },
      { title: "펫 보험 가입 가이드 — 보장 항목 비교", description: "주요 펫 보험사의 보장 범위, 보험료, 면책 조항 비교 분석.", tags: ["펫보험", "보장", "비교"], animal: "both", difficulty: "basic", viralScore: 86 },
      { title: "광견병 예방접종 — 법적 의무와 접종 주기", description: "광견병 예방접종이 법적 의무인 이유와 1년 주기 접종의 중요성.", tags: ["광견병", "의무접종", "법률"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "백신 부작용 — 알아야 할 증상과 대처", description: "접종 후 발생할 수 있는 부종, 알레르기 반응, 아나필락시스 대처법.", tags: ["백신부작용", "알레르기", "응급"], animal: "both", difficulty: "intermediate", viralScore: 83 },
      { title: "강아지 사회화 기간과 건강 관리", description: "생후 3~14주 사회화 시기의 건강 관리와 예방접종 완료 전 산책 논쟁.", tags: ["사회화", "퍼피", "예방접종"], animal: "dog", difficulty: "intermediate", viralScore: 79 },
      { title: "비만 예방을 위한 급여량 관리", description: "적정 체중 유지를 위한 칼로리 계산과 간식 제한 가이드.", tags: ["비만예방", "급여량", "체중관리"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "실내 고양이 운동 부족 해결법", description: "캣타워, 인터랙티브 장난감, 놀이 시간 확보로 운동량 늘리기.", tags: ["운동", "실내묘", "비만예방"], animal: "cat", difficulty: "basic", viralScore: 78 },
      { title: "반려동물 여행 시 건강 체크리스트", description: "해외 여행 시 필요한 서류, 예방접종, 검역 절차 총정리.", tags: ["여행", "검역", "서류"], animal: "both", difficulty: "intermediate", viralScore: 75 },
      { title: "화학적 거세 vs 외과적 중성화", description: "수프렐로린 임플란트를 이용한 일시적 거세와 영구적 수술의 비교.", tags: ["거세", "수프렐로린", "비교"], animal: "dog", difficulty: "advanced", viralScore: 74 },
      { title: "항체 역가 검사 — 추가 접종 필요 여부 확인", description: "매년 재접종 대신 항체 역가를 확인하여 과잉 접종을 피하는 방법.", tags: ["항체역가", "과잉접종", "예방"], animal: "both", difficulty: "advanced", viralScore: 76 },
      { title: "반려동물 구강 검진의 중요성", description: "3세 이상 반려동물의 80%가 치주질환이 있다는 통계와 예방법.", tags: ["구강검진", "치주질환", "예방"], animal: "both", difficulty: "basic", viralScore: 80 },
      { title: "강아지 발바닥 관리 — 패드 보호", description: "여름 아스팔트 화상, 겨울 제설제 자극으로부터 패드를 보호하는 방법.", tags: ["발바닥", "패드", "계절관리"], animal: "dog", difficulty: "basic", viralScore: 77 },
      { title: "고양이 실내 환경 안전 점검", description: "창문 추락, 독성 식물, 작은 물건 삼킴 등 실내 위험 요소 체크리스트.", tags: ["안전", "실내환경", "사고예방"], animal: "cat", difficulty: "basic", viralScore: 82 },
      { title: "반려동물 치과 스케일링 시기와 비용", description: "전신마취 하 스케일링의 필요성, 적정 시기, 비용 범위 안내.", tags: ["스케일링", "치과", "비용"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "강아지 눈물자국 관리와 예방", description: "눈물자국의 원인(누관 막힘, 알레르기)과 관리 방법, 식이 조절 팁.", tags: ["눈물자국", "눈관리", "미용"], animal: "dog", difficulty: "basic", viralScore: 79 },
      { title: "예방 의학 vs 치료 의학 — 비용 비교", description: "예방에 투자하는 비용이 치료비의 1/10에 불과하다는 통계와 분석.", tags: ["비용비교", "예방투자", "경제성"], animal: "both", difficulty: "basic", viralScore: 85 },
    ]
  },
  {
    id: "vet-dental", name: "치과", icon: "🦷",
    topics: [
      { title: "반려동물 치주질환의 4단계", description: "치은염부터 중증 치주염까지 단계별 증상과 치료 방법 정리.", tags: ["치주질환", "단계", "치과"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "강아지 이빨 빠지는 시기 — 유치에서 영구치까지", description: "생후 3~7개월 유치 탈락과 영구치 맹출 과정, 이중 치열 대처법.", tags: ["유치", "영구치", "퍼피"], animal: "dog", difficulty: "basic", viralScore: 80 },
      { title: "고양이 치아흡수성 병변(FORL)", description: "고양이에서 흔한 FORL의 원인, X-ray 진단, 발치 치료.", tags: ["FORL", "치아흡수", "고양이치과"], animal: "cat", difficulty: "advanced", viralScore: 73 },
      { title: "전신마취 스케일링 — 안전한가?", description: "스케일링 시 전신마취가 필수인 이유와 마취 위험성에 대한 오해와 진실.", tags: ["스케일링", "전신마취", "안전"], animal: "both", difficulty: "intermediate", viralScore: 86 },
      { title: "무마취 스케일링의 위험성", description: "무마취 치석 제거가 반려동물에게 해로운 이유와 수의학계의 입장.", tags: ["무마취", "스케일링", "위험"], animal: "both", difficulty: "intermediate", viralScore: 89 },
      { title: "구취의 원인 — 단순 입냄새 vs 질환 신호", description: "치석, 구내염, 신장질환, 당뇨 등 구취를 유발하는 다양한 원인 감별.", tags: ["구취", "입냄새", "진단"], animal: "both", difficulty: "basic", viralScore: 83 },
      { title: "강아지 칫솔질 단계별 트레이닝", description: "손가락 터치부터 칫솔 적응까지 2주 프로그램으로 칫솔질 습관 만들기.", tags: ["칫솔질", "트레이닝", "습관"], animal: "dog", difficulty: "basic", viralScore: 81 },
      { title: "치과용 간식과 장난감의 실제 효과", description: "VOHC 인증 치과 간식의 치석 감소 효과와 올바른 선택 기준.", tags: ["치과간식", "VOHC", "치석"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "발치 수술 후 관리 가이드", description: "발치 후 연식 급여 기간, 항생제 복용, 재진 일정 안내.", tags: ["발치", "수술후", "관리"], animal: "both", difficulty: "intermediate", viralScore: 72 },
      { title: "강아지 부정교합 — 치과 교정이 필요한 경우", description: "심한 부정교합으로 구강 손상이 발생할 때의 교정 치료 옵션.", tags: ["부정교합", "교정", "치과"], animal: "dog", difficulty: "advanced", viralScore: 68 },
      { title: "치석 형성 과정 — 플라크에서 치석까지", description: "치석이 만들어지는 72시간의 과정과 매일 관리가 중요한 이유.", tags: ["치석", "플라크", "형성과정"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "구강 종양의 초기 증상", description: "잇몸 부종, 출혈, 식사 곤란 등 구강 종양을 의심해야 할 증상.", tags: ["구강종양", "암", "초기증상"], animal: "both", difficulty: "intermediate", viralScore: 82 },
      { title: "고양이 잇몸 질환 관리", description: "FeLV, FIV 양성 고양이에서 특히 심한 잇몸 질환의 관리 전략.", tags: ["잇몸", "FeLV", "고양이"], animal: "cat", difficulty: "advanced", viralScore: 74 },
      { title: "치과 방사선(X-ray)이 필요한 이유", description: "눈에 보이는 치아 위 부분만으로는 알 수 없는 치근 문제 진단.", tags: ["치과X선", "진단", "치근"], animal: "both", difficulty: "intermediate", viralScore: 71 },
      { title: "반려동물 치약 선택 가이드", description: "사람 치약은 금물! 반려동물 전용 치약의 성분과 추천 제품.", tags: ["치약", "제품추천", "안전"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "치과 질환과 전신 건강의 연관성", description: "치주질환 세균이 심장, 간, 신장에 영향을 미치는 기전 설명.", tags: ["전신건강", "세균", "합병증"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "소형견 치과 질환이 많은 이유", description: "작은 턱에 비해 많은 치아, 치아 밀집으로 인한 치주질환 취약성.", tags: ["소형견", "치과취약", "견종별"], animal: "dog", difficulty: "intermediate", viralScore: 77 },
      { title: "시니어 반려동물의 구강 관리", description: "노령 동물의 마취 위험 평가와 구강 관리의 중요성 간 균형.", tags: ["시니어", "구강관리", "마취위험"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "잇몸 색깔로 건강 상태 파악하기", description: "분홍(정상), 창백(빈혈), 노랑(황달), 파랑(청색증) 잇몸색 해석법.", tags: ["잇몸색", "건강지표", "진단"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "양치질 대안 — 구강 스프레이와 워터 첨가제", description: "칫솔질이 불가능할 때 사용할 수 있는 대안적 구강 관리 제품.", tags: ["구강스프레이", "대안", "구강관리"], animal: "both", difficulty: "basic", viralScore: 76 },
      { title: "강아지 뼈다귀 간식의 치아 손상 위험", description: "단단한 뼈, 사슴뿔 간식으로 인한 치아 파절 사례와 안전한 대안.", tags: ["뼈간식", "치아파절", "안전"], animal: "dog", difficulty: "basic", viralScore: 85 },
      { title: "고양이 구내염 — 전발치 후 예후", description: "심한 구내염에서 전체 발치 수술 후 80%가 호전되는 연구 결과.", tags: ["구내염", "전발치", "예후"], animal: "cat", difficulty: "advanced", viralScore: 76 },
      { title: "유치 잔존(잔류유치) 대처법", description: "영구치가 나왔는데 유치가 빠지지 않을 때 발치의 필요성.", tags: ["잔류유치", "발치", "퍼피"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "치과 시술 비용 가이드", description: "스케일링, 발치, 구강 수술 등 시술별 평균 비용 범위 안내.", tags: ["비용", "치과시술", "가격"], animal: "both", difficulty: "basic", viralScore: 87 },
      { title: "홈 구강 검진 방법", description: "집에서 정기적으로 반려동물의 치아와 잇몸을 검사하는 방법.", tags: ["홈검진", "구강검진", "자가진단"], animal: "both", difficulty: "basic", viralScore: 78 },
      { title: "치은 증식증 — 잇몸이 치아를 덮을 때", description: "특정 견종과 약물로 인한 잇몸 과증식의 원인과 외과적 처치.", tags: ["치은증식", "잇몸", "외과"], animal: "dog", difficulty: "advanced", viralScore: 66 },
      { title: "에나멜 저형성증", description: "퍼피 시절 고열, 영양결핍으로 인한 법랑질 형성 부전과 관리.", tags: ["에나멜", "법랑질", "발달"], animal: "both", difficulty: "advanced", viralScore: 64 },
      { title: "치과 질환 예방을 위한 사료 선택", description: "크로켓 크기, 질감, 치석 억제 코팅 등 구강 건강을 고려한 사료.", tags: ["사료", "치과예방", "크로켓"], animal: "both", difficulty: "basic", viralScore: 73 },
      { title: "반려동물 입 벌리기 훈련", description: "구강 검진과 칫솔질을 위해 자발적으로 입을 벌리도록 훈련하는 방법.", tags: ["훈련", "구강관리", "습관화"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "치과 전문 동물병원 선택 기준", description: "치과 전문 장비(치과 X-ray, 고속 핸드피스)를 갖춘 병원 선별법.", tags: ["전문병원", "장비", "선택기준"], animal: "both", difficulty: "basic", viralScore: 79 },
    ]
  },
  {
    id: "vet-emergency", name: "응급의학", icon: "🚑",
    topics: [
      { title: "반려동물 CPR(심폐소생술) 방법", description: "호흡과 심장이 멈췄을 때 골든타임 내 CPR을 시행하는 정확한 방법.", tags: ["CPR", "심폐소생술", "응급"], animal: "both", difficulty: "intermediate", viralScore: 93 },
      { title: "초콜릿 중독 — 종류별 독성과 응급 처치", description: "다크 초콜릿, 밀크 초콜릿, 화이트 초콜릿의 테오브로민 함량별 위험도.", tags: ["초콜릿", "중독", "응급처치"], animal: "dog", difficulty: "basic", viralScore: 95 },
      { title: "자일리톨 중독 — 15분 내 저혈당 위기", description: "무설탕 껌 한 알이 치명적! 자일리톨 섭취 후 증상과 즉각 대응법.", tags: ["자일리톨", "중독", "저혈당"], animal: "dog", difficulty: "basic", viralScore: 94 },
      { title: "포도/건포도 중독 — 급성 신부전 위험", description: "포도 한 알로도 급성 신부전이 발생할 수 있는 이유와 응급 대처.", tags: ["포도", "신부전", "중독"], animal: "dog", difficulty: "basic", viralScore: 92 },
      { title: "양파/마늘 중독 — 하인츠 소체 빈혈", description: "양파과 식물이 적혈구를 파괴하는 기전과 소량 지속 섭취의 위험성.", tags: ["양파", "빈혈", "중독"], animal: "both", difficulty: "intermediate", viralScore: 86 },
      { title: "열사병 응급 처치 — 체온 40도 이상", description: "여름철 차 안 방치, 과도한 운동 후 열사병 증상과 즉각 냉각법.", tags: ["열사병", "응급", "여름"], animal: "both", difficulty: "basic", viralScore: 91 },
      { title: "이물질 삼킴 — 내시경 vs 수술 판단", description: "양말, 장난감, 뼈 조각 삼킴 시 X-ray 확인 후 제거 방법 결정 과정.", tags: ["이물질", "삼킴", "내시경"], animal: "both", difficulty: "intermediate", viralScore: 88 },
      { title: "출혈 시 지혈하는 방법", description: "직접 압박, 지혈대 사용, 발톱 출혈 시 퀵스탑 사용법 안내.", tags: ["출혈", "지혈", "응급"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "골절 시 응급 고정과 이송", description: "골절 의심 시 현장 고정 방법과 동물병원까지 안전하게 이송하는 요령.", tags: ["골절", "고정", "이송"], animal: "both", difficulty: "intermediate", viralScore: 79 },
      { title: "화상 응급 처치 — 열탕, 화학, 전기", description: "화상 종류별 초기 처치법과 절대 하면 안 되는 행동(연고, 버터 도포).", tags: ["화상", "응급처치", "초기대응"], animal: "both", difficulty: "intermediate", viralScore: 77 },
      { title: "뱀에 물렸을 때 대처법", description: "독사 교상 시 움직임 최소화, 상처 세척 금지 등 올바른 응급 대응.", tags: ["뱀교상", "독사", "응급"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "벌 쏘임 — 알레르기 반응과 아나필락시스", description: "벌 쏘임 후 얼굴 부종, 호흡 곤란 등 심각한 알레르기 반응 대처법.", tags: ["벌쏘임", "알레르기", "아나필락시스"], animal: "both", difficulty: "intermediate", viralScore: 81 },
      { title: "GDV(위확장-염전) — 대형견의 생명 위협", description: "위가 뒤틀리는 GDV의 초기 증상과 수술적 응급 대응의 중요성.", tags: ["GDV", "위염전", "대형견"], animal: "dog", difficulty: "advanced", viralScore: 90 },
      { title: "경련/발작 시 대처법", description: "발작 중 입에 손 넣지 않기, 주변 정리, 시간 측정 등 올바른 대응.", tags: ["발작", "경련", "신경과"], animal: "both", difficulty: "intermediate", viralScore: 84 },
      { title: "교통사고 후 응급 대처", description: "외부 출혈 확인, 척추 손상 주의, 안전한 이송 방법 총정리.", tags: ["교통사고", "외상", "이송"], animal: "both", difficulty: "intermediate", viralScore: 83 },
      { title: "익사 위기 — 수영 중 사고 대처", description: "반려동물이 물에 빠졌을 때 구조 후 즉시 해야 할 응급 처치.", tags: ["익사", "수영", "응급"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "저체온증 — 겨울철 장시간 야외 노출", description: "체온 37도 이하로 떨어질 때의 보온 방법과 병원 이송 기준.", tags: ["저체온증", "겨울", "체온관리"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "눈 외상 — 돌출, 이물질, 긁힘", description: "안구 손상 시 만지지 않기, 엘리자베스 칼라 착용 후 즉시 내원.", tags: ["눈외상", "안과", "응급"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "전기 감전 — 전선 물어뜯기 사고", description: "퍼피가 전선을 물어 감전 시 폐부종, 심부정맥 등 응급 대처.", tags: ["감전", "전선", "퍼피"], animal: "both", difficulty: "intermediate", viralScore: 80 },
      { title: "살충제/제초제 중독 대처", description: "산책 중 제초제 접촉이나 살충제 섭취 시 응급 처치와 독극물 센터 연락.", tags: ["살충제", "중독", "산책"], animal: "both", difficulty: "intermediate", viralScore: 82 },
      { title: "반려동물 응급 키트 구성", description: "붕대, 지혈제, 체온계, 주사기 등 가정에 구비해야 할 응급 키트 리스트.", tags: ["응급키트", "구성품", "준비"], animal: "both", difficulty: "basic", viralScore: 85 },
      { title: "야간 응급 동물병원 찾는 방법", description: "24시간 응급 동물병원 검색 앱과 사전에 연락처를 저장해두는 요령.", tags: ["야간응급", "병원검색", "준비"], animal: "both", difficulty: "basic", viralScore: 83 },
      { title: "복어독(테트로도톡신) 중독", description: "해변 산책 중 복어 사체 접촉 시 치명적인 신경독 중독 대처.", tags: ["복어독", "해변", "신경독"], animal: "dog", difficulty: "advanced", viralScore: 75 },
      { title: "두꺼비 독(부포톡신) 중독", description: "두꺼비를 물었을 때 구강 내 독소 제거와 심장 독성 응급 대응.", tags: ["두꺼비", "부포톡신", "독성"], animal: "dog", difficulty: "intermediate", viralScore: 73 },
      { title: "고양이 추락 사고(고층 증후군)", description: "고층 아파트에서 추락한 고양이의 흔한 손상 패턴과 응급 대처.", tags: ["추락", "고층증후군", "고양이"], animal: "cat", difficulty: "intermediate", viralScore: 84 },
      { title: "사람 약물 오섭취 시 대처법", description: "아세트아미노펜, 이부프로펜 등 사람 약을 먹었을 때 독성과 대응.", tags: ["약물중독", "사람약", "응급"], animal: "both", difficulty: "intermediate", viralScore: 87 },
      { title: "동물 교상(개 물림) 응급 처치", description: "다른 개에게 물렸을 때 상처 세척, 감염 예방, 봉합 판단 기준.", tags: ["교상", "물림", "감염"], animal: "both", difficulty: "intermediate", viralScore: 79 },
      { title: "구토 유발 — 해야 할 때와 하면 안 될 때", description: "이물질 섭취 후 구토 유발이 적절한 상황과 부식성 물질 섭취 시 금기.", tags: ["구토유발", "독극물", "판단"], animal: "both", difficulty: "advanced", viralScore: 81 },
      { title: "쇼크 증상 인식과 응급 대처", description: "창백한 잇몸, 빠른 심박, 차가운 사지 등 쇼크 초기 증상 판별.", tags: ["쇼크", "순환부전", "응급"], animal: "both", difficulty: "advanced", viralScore: 78 },
      { title: "반려동물 하임리히법(기도 이물 제거)", description: "사료나 장난감이 기도에 걸렸을 때 체급별 하임리히법 시행 방법.", tags: ["하임리히", "기도폐쇄", "질식"], animal: "both", difficulty: "intermediate", viralScore: 86 },
    ]
  },
  {
    id: "vet-geriatric", name: "노령동물학", icon: "👴",
    topics: [
      { title: "시니어 반려동물의 기준 — 몇 살부터?", description: "소형견 10세, 대형견 6세, 고양이 11세부터 시니어로 분류하는 기준.", tags: ["시니어", "연령기준", "노령"], animal: "both", difficulty: "basic", viralScore: 78 },
      { title: "노령견 인지기능장애(CCD) — 치매 증상", description: "밤에 짖기, 방향감각 상실, 가족 못 알아보기 등 강아지 치매 증상.", tags: ["치매", "인지기능", "CCD"], animal: "dog", difficulty: "intermediate", viralScore: 89 },
      { title: "시니어 고양이의 행동 변화", description: "활동량 감소, 식욕 변화, 화장실 실수 등 노령 고양이의 변화 해석.", tags: ["시니어", "행동변화", "고양이"], animal: "cat", difficulty: "basic", viralScore: 77 },
      { title: "노령 동물의 통증 관리 — 만성 통증 신호", description: "숨는 행동, 으르렁, 움직임 감소 등 통증을 숨기는 동물의 신호.", tags: ["통증", "만성통증", "관리"], animal: "both", difficulty: "intermediate", viralScore: 83 },
      { title: "시니어 전용 사료로 전환해야 할 시기", description: "저칼로리, 관절 보조 성분, 항산화제가 강화된 시니어 사료 선택 기준.", tags: ["시니어사료", "전환", "영양"], animal: "both", difficulty: "basic", viralScore: 76 },
      { title: "노령견 산책 — 적절한 운동량 조절", description: "관절과 심장에 부담을 주지 않는 시니어 맞춤형 산책 시간과 강도.", tags: ["산책", "운동", "시니어"], animal: "dog", difficulty: "basic", viralScore: 80 },
      { title: "시니어 고양이 환경 조성 — 접근성 높이기", description: "계단형 발판, 낮은 화장실, 미끄럼 방지 매트 등 노령묘 환경 개선.", tags: ["환경조성", "접근성", "시니어"], animal: "cat", difficulty: "basic", viralScore: 79 },
      { title: "노령 동물 건강검진 — 6개월마다 체크", description: "혈액검사, 요검사, X-ray, 혈압 측정 등 시니어 정기 검진 항목.", tags: ["건강검진", "정기", "시니어"], animal: "both", difficulty: "basic", viralScore: 82 },
      { title: "시니어 반려동물의 수면 패턴 변화", description: "수면 시간 증가, 밤낮 역전 등 노령 동물의 수면 변화와 대응.", tags: ["수면", "밤낮역전", "시니어"], animal: "both", difficulty: "basic", viralScore: 74 },
      { title: "관절 보조제 — 시니어에게 효과적인 성분", description: "글루코사민, MSM, 초록입홍합, 오메가3 등 관절 건강 보조제 비교.", tags: ["관절보조제", "시니어", "성분비교"], animal: "both", difficulty: "intermediate", viralScore: 77 },
      { title: "노령견 실금 — 원인과 관리 방법", description: "호르몬성, 신경성, 인지기능 저하로 인한 실금의 감별과 관리.", tags: ["실금", "비뇨기", "시니어"], animal: "dog", difficulty: "intermediate", viralScore: 75 },
      { title: "시니어 반려동물의 마취 위험 평가", description: "고령 동물 수술 시 마취 전 검사 항목과 위험도 분류(ASA 등급).", tags: ["마취", "수술", "위험평가"], animal: "both", difficulty: "advanced", viralScore: 73 },
      { title: "노령 고양이 갑상선 기능항진증 관리", description: "시니어 고양이에서 흔한 갑상선 기능항진증의 약물, 식이, 방사선 치료.", tags: ["갑상선", "시니어", "관리"], animal: "cat", difficulty: "intermediate", viralScore: 76 },
      { title: "치매 예방을 위한 뇌 활성화 놀이", description: "노즈워크, 퍼즐 피더, 새로운 산책 경로 등 인지 자극 활동.", tags: ["뇌활성화", "치매예방", "놀이"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "통증 관리 약물 — NSAIDs와 부작용", description: "멜록시캄, 카프로펜 등 소염진통제의 효과와 간/신장 부작용 모니터링.", tags: ["NSAIDs", "통증약", "부작용"], animal: "both", difficulty: "advanced", viralScore: 72 },
      { title: "시니어 반려동물의 치과 관리", description: "치주질환이 진행된 노령 동물의 마취 스케일링 결정 기준.", tags: ["치과", "시니어", "마취"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "호스피스 케어 — 말기 환자의 삶의 질", description: "완치가 어려운 질환에서 통증 관리와 삶의 질을 유지하는 호스피스 접근.", tags: ["호스피스", "말기", "삶의질"], animal: "both", difficulty: "intermediate", viralScore: 81 },
      { title: "안락사 결정 — 보호자를 위한 가이드", description: "안락사를 고려해야 할 시점, 수의사와의 상담, 감정적 준비에 대한 안내.", tags: ["안락사", "의사결정", "보호자"], animal: "both", difficulty: "intermediate", viralScore: 90 },
      { title: "펫 로스 — 반려동물 상실 후 애도 과정", description: "반려동물을 잃은 후 겪는 슬픔의 단계와 건강한 애도 방법.", tags: ["펫로스", "슬픔", "애도"], animal: "both", difficulty: "basic", viralScore: 92 },
      { title: "시니어 동물 입양의 가치", description: "노령 동물 입양의 장점과 보람, 특별한 케어 노하우.", tags: ["시니어입양", "가치", "케어"], animal: "both", difficulty: "basic", viralScore: 85 },
      { title: "노령견 근육량 유지를 위한 운동", description: "수중 트레드밀, 밸런스 보드 등 시니어에게 적합한 재활 운동.", tags: ["근육량", "재활운동", "시니어"], animal: "dog", difficulty: "intermediate", viralScore: 76 },
      { title: "시니어 반려동물 체중 관리 전략", description: "대사량 감소에 맞춘 칼로리 조절과 체중 유지·감량 전략.", tags: ["체중관리", "시니어", "칼로리"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "노령 동물의 시력 저하와 적응", description: "백내장, 핵경화증 등으로 시력이 떨어진 동물의 환경 적응 돕기.", tags: ["시력", "백내장", "적응"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "노령 동물의 청력 저하 대응", description: "청력 감소 시 수신호 훈련, 진동 알림 등 의사소통 대안.", tags: ["청력", "수신호", "적응"], animal: "both", difficulty: "intermediate", viralScore: 71 },
      { title: "시니어 반려동물과의 유대 강화", description: "노령기에도 유대감을 유지하는 부드러운 마사지, 조용한 동행 등.", tags: ["유대감", "교감", "시니어"], animal: "both", difficulty: "basic", viralScore: 80 },
      { title: "다묘/다견 가정의 시니어 케어", description: "젊은 동물과 함께 사는 시니어의 스트레스 관리와 분리 공간 확보.", tags: ["다견", "다묘", "시니어"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "시니어 동물의 피부 변화", description: "탈모, 건조함, 종괴 발생 등 노령기 피부 변화와 주의 사항.", tags: ["피부", "노화", "시니어"], animal: "both", difficulty: "basic", viralScore: 70 },
      { title: "CBD 오일의 시니어 통증 관리 효과", description: "반려동물 CBD 사용에 대한 현재까지의 연구 결과와 수의사 견해.", tags: ["CBD", "통증", "대안치료"], animal: "both", difficulty: "advanced", viralScore: 82 },
      { title: "노령 동물 보조 기구 — 휠체어, 보행기", description: "뒷다리 마비, 심한 관절염 동물을 위한 보조 기구 선택과 적응.", tags: ["휠체어", "보조기구", "재활"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "무지개다리 기념 — 추모 방법과 문화", description: "반려동물 화장, 수목장, 추모 다이아몬드 등 다양한 추모 문화 소개.", tags: ["추모", "무지개다리", "문화"], animal: "both", difficulty: "basic", viralScore: 86 },
    ]
  },
  {
    id: "vet-dermatology", name: "피부과", icon: "🩹",
    topics: [
      { title: "강아지 아토피 피부염 — 원인과 관리", description: "환경 알레르겐에 의한 만성 아토피의 증상, 진단, 장기 관리 전략.", tags: ["아토피", "알레르기", "피부"], animal: "dog", difficulty: "intermediate", viralScore: 87 },
      { title: "고양이 호산구성 육아종 복합체", description: "고양이 입술, 턱, 복부에 발생하는 호산구성 병변의 원인과 치료.", tags: ["호산구성", "육아종", "고양이피부"], animal: "cat", difficulty: "advanced", viralScore: 72 },
      { title: "피부 사상균(곰팡이) 감염 — 링웜", description: "원형 탈모를 일으키는 곰팡이 감염의 진단, 치료, 환경 소독법.", tags: ["링웜", "곰팡이", "전염"], animal: "both", difficulty: "intermediate", viralScore: 81 },
      { title: "벼룩 알레르기 피부염(FAD)", description: "벼룩 한 마리에도 심한 가려움이 발생하는 벼룩 알레르기의 기전.", tags: ["벼룩", "알레르기", "FAD"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "농피증 — 세균성 피부 감염", description: "포도상구균에 의한 농피증의 단계별 치료와 항생제 내성 문제.", tags: ["농피증", "세균감염", "항생제"], animal: "both", difficulty: "intermediate", viralScore: 75 },
      { title: "모낭충증(데모덱스) — 면역 저하와의 관계", description: "모낭충 과증식의 원인과 전신형/국소형 치료 전략.", tags: ["모낭충", "데모덱스", "면역"], animal: "dog", difficulty: "intermediate", viralScore: 77 },
      { title: "옴(개선충) — 극심한 가려움의 원인", description: "개선충 감염 시 심한 가려움, 탈모, 딱지가 발생하는 기전과 치료.", tags: ["옴", "개선충", "기생충"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "핫스팟(급성 습성 피부염) 응급 처치", description: "갑자기 발생하는 빨갛고 습한 피부 병변의 원인과 즉각적 처치.", tags: ["핫스팟", "급성", "습성피부염"], animal: "dog", difficulty: "basic", viralScore: 80 },
      { title: "효모 감염(말라세지아) — 검은 귀지의 원인", description: "귀와 피부의 효모 과증식으로 인한 기름진 피부, 악취의 치료.", tags: ["효모", "말라세지아", "귀감염"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "강아지 탈모의 10가지 원인", description: "알레르기, 호르몬, 감염, 스트레스 등 탈모를 유발하는 다양한 원인.", tags: ["탈모", "원인", "감별진단"], animal: "dog", difficulty: "intermediate", viralScore: 84 },
      { title: "쿠싱 관련 피부 증상", description: "부신피질 호르몬 과다로 인한 대칭성 탈모, 피부 석회화 등 피부 변화.", tags: ["쿠싱", "호르몬", "탈모"], animal: "dog", difficulty: "advanced", viralScore: 69 },
      { title: "갑상선 저하증의 피부 증상", description: "갑상선 기능 저하로 인한 탈모, 피부 비후, 색소침착 변화.", tags: ["갑상선", "탈모", "호르몬"], animal: "dog", difficulty: "advanced", viralScore: 68 },
      { title: "식이 알레르기 vs 환경 알레르기 감별", description: "가려움 부위, 계절성, 제거식이 반응 등으로 알레르기 원인 감별.", tags: ["알레르기감별", "식이", "환경"], animal: "both", difficulty: "intermediate", viralScore: 82 },
      { title: "아포퀠(오클라시티닙)의 효과와 부작용", description: "아토피 치료제 아포퀠의 작용 기전, 효과, 장기 사용 안전성.", tags: ["아포퀠", "아토피약", "부작용"], animal: "dog", difficulty: "advanced", viralScore: 80 },
      { title: "사이토포인트(항체 치료)란?", description: "IL-31을 차단하는 항체 주사로 가려움을 줄이는 새로운 치료법.", tags: ["사이토포인트", "항체", "가려움"], animal: "dog", difficulty: "advanced", viralScore: 79 },
      { title: "피부 종괴 — 양성 vs 악성 감별", description: "지방종, 비만세포종, 조직구종 등 흔한 피부 종괴의 특성과 검사.", tags: ["종괴", "종양", "감별"], animal: "both", difficulty: "intermediate", viralScore: 83 },
      { title: "고양이 여드름 — 턱 검은 점의 정체", description: "고양이 턱에 생기는 여드름의 원인(식기 재질, 세균)과 관리법.", tags: ["여드름", "고양이", "턱"], animal: "cat", difficulty: "basic", viralScore: 81 },
      { title: "반려동물 발 사이 피부염", description: "지간 피부염의 원인(알레르기, 효모, 이물질)과 발 씻기 관리.", tags: ["지간", "발피부염", "관리"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "피부 긁적 검사와 세포 검사", description: "피부과 진단에 사용되는 기본 검사법의 종류와 각각의 역할.", tags: ["긁적검사", "세포검사", "진단"], animal: "both", difficulty: "intermediate", viralScore: 67 },
      { title: "약욕(메디케이티드 샴푸) 올바른 사용법", description: "항균, 항진균 약용 샴푸의 접촉 시간 10분 룰과 주의사항.", tags: ["약욕", "샴푸", "피부치료"], animal: "both", difficulty: "basic", viralScore: 74 },
      { title: "강아지 목욕 주기 — 너무 잦으면 역효과", description: "피부 장벽을 보호하는 적절한 목욕 빈도와 샴푸 선택 가이드.", tags: ["목욕", "피부장벽", "그루밍"], animal: "dog", difficulty: "basic", viralScore: 78 },
      { title: "고양이 과도한 그루밍(심인성 탈모)", description: "스트레스로 인한 과다 그루밍과 의학적 원인 감별 진단.", tags: ["과다그루밍", "스트레스", "탈모"], animal: "cat", difficulty: "intermediate", viralScore: 80 },
      { title: "피부 알레르기 검사 — 혈액 vs 피내", description: "알레르기 원인을 찾기 위한 검사 방법별 정확도와 비용 비교.", tags: ["알레르기검사", "피내검사", "혈액검사"], animal: "both", difficulty: "advanced", viralScore: 73 },
      { title: "면역 치료(감작 요법)로 아토피 근본 치료", description: "알레르겐 감작 주사를 통한 면역 조절 치료의 과정과 성공률.", tags: ["면역치료", "감작요법", "아토피"], animal: "both", difficulty: "advanced", viralScore: 75 },
      { title: "계절성 알레르기 관리 달력", description: "봄 꽃가루, 여름 잔디, 가을 잡초 등 계절별 알레르겐과 대응 전략.", tags: ["계절알레르기", "꽃가루", "관리"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "피부 보습 — 건조한 피부 관리", description: "겨울철 건조해지는 반려동물 피부를 위한 보습제와 습도 관리.", tags: ["보습", "건조", "겨울케어"], animal: "both", difficulty: "basic", viralScore: 72 },
      { title: "귀 혈종(이혈종) 원인과 치료", description: "귀를 심하게 긁거나 흔들어 발생하는 혈종의 외과적 치료.", tags: ["이혈종", "귀", "외과"], animal: "both", difficulty: "intermediate", viralScore: 71 },
      { title: "발바닥 패드 과각화증", description: "패드가 두껍고 갈라지는 과각화증의 원인과 보습 관리법.", tags: ["패드", "과각화증", "발바닥"], animal: "dog", difficulty: "intermediate", viralScore: 66 },
      { title: "피부 상처 관리 — 소독과 드레싱", description: "찰과상, 열상 등 가벼운 피부 상처의 가정 내 소독과 관리.", tags: ["상처", "소독", "드레싱"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "색소 변화 — 코, 입술, 피부 변색의 의미", description: "멜라닌 변화, 자가면역 질환 등으로 인한 피부 색소 변화 해석.", tags: ["색소변화", "멜라닌", "자가면역"], animal: "both", difficulty: "intermediate", viralScore: 70 },
    ]
  },
  {
    id: "vet-ophthalmology", name: "안과/기타", icon: "👁️",
    topics: [
      { title: "강아지 백내장 — 수술이 유일한 치료법", description: "수정체 혼탁으로 시력을 잃는 백내장의 진단과 인공 수정체 수술.", tags: ["백내장", "안과", "수술"], animal: "dog", difficulty: "intermediate", viralScore: 79 },
      { title: "핵경화증 vs 백내장 구별법", description: "노령 동물의 눈이 뿌옇게 보이는 핵경화증과 백내장의 차이.", tags: ["핵경화증", "백내장", "구별"], animal: "both", difficulty: "intermediate", viralScore: 74 },
      { title: "건성 안증후군(안구건조증)", description: "눈물 분비 부족으로 인한 각막 손상과 인공 눈물 치료.", tags: ["안구건조증", "눈물", "각막"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "각막 궤양 — 긁힘에서 천공까지", description: "각막 손상의 단계별 치료와 깊은 궤양 시 응급 수술의 필요성.", tags: ["각막궤양", "응급", "안과"], animal: "both", difficulty: "intermediate", viralScore: 78 },
      { title: "체리아이(제3안검 탈출)", description: "제3안검선이 튀어나오는 체리아이의 원인과 매몰 수술 치료.", tags: ["체리아이", "제3안검", "수술"], animal: "dog", difficulty: "intermediate", viralScore: 76 },
      { title: "녹내장 — 안압 상승의 위험성", description: "급성 녹내장의 통증과 실명 위험, 안압 검사의 중요성.", tags: ["녹내장", "안압", "실명"], animal: "both", difficulty: "advanced", viralScore: 77 },
      { title: "안구 적출 — 두려워하지 마세요", description: "심한 안구 질환에서 적출이 필요한 상황과 수술 후 적응 과정.", tags: ["안구적출", "수술", "적응"], animal: "both", difficulty: "intermediate", viralScore: 75 },
      { title: "단두종의 안과 질환 — 안구 돌출", description: "시추, 퍼그 등 단두종에서 흔한 안구 돌출과 외상성 탈구.", tags: ["단두종", "안구돌출", "견종별"], animal: "dog", difficulty: "intermediate", viralScore: 80 },
      { title: "눈 분비물 — 색깔별 원인 해석", description: "투명(정상), 노란/초록(감염), 갈색(눈물자국)별 원인과 대처.", tags: ["눈분비물", "감염", "진단"], animal: "both", difficulty: "basic", viralScore: 81 },
      { title: "고양이 허피스 관련 안과 질환", description: "고양이 허피스 바이러스로 인한 각막염, 결막염의 만성 관리.", tags: ["허피스", "안과", "만성"], animal: "cat", difficulty: "intermediate", viralScore: 74 },
      { title: "반려동물 귀 감염의 3가지 유형", description: "외이염, 중이염, 내이염의 원인과 증상, 치료법 비교.", tags: ["귀감염", "외이염", "중이염"], animal: "both", difficulty: "intermediate", viralScore: 77 },
      { title: "귀진드기(이개선충) 감염과 치료", description: "귀를 심하게 긁는 원인인 귀진드기의 진단과 구충제 치료.", tags: ["귀진드기", "이개선충", "기생충"], animal: "both", difficulty: "basic", viralScore: 75 },
      { title: "만성 외이염의 원인과 장기 관리", description: "반복되는 외이염의 근본 원인(알레르기, 구조적 문제) 파악과 관리.", tags: ["만성외이염", "알레르기", "장기관리"], animal: "both", difficulty: "intermediate", viralScore: 73 },
      { title: "전정기관 질환 — 머리 기울임 증상", description: "말초성·중추성 전정질환의 증상(머리 기울임, 회전)과 감별.", tags: ["전정질환", "머리기울임", "신경과"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "반려동물 항문낭 관리", description: "항문낭 분비물 짜기, 농양 예방, 수술적 제거가 필요한 경우.", tags: ["항문낭", "관리", "농양"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "구토와 설사 — 가정 관리 vs 병원 방문 기준", description: "단순 소화불량과 심각한 질환을 구별하는 경고 신호 체크리스트.", tags: ["구토", "설사", "판단기준"], animal: "both", difficulty: "basic", viralScore: 86 },
      { title: "반려동물 해열제 — 사람 약 절대 금지", description: "아세트아미노펜이 고양이에게 치명적인 이유와 안전한 해열 방법.", tags: ["해열제", "약물독성", "금지"], animal: "both", difficulty: "basic", viralScore: 84 },
      { title: "강아지 역재채기(리버스 스니징)", description: "흡입성 재채기의 원인, 대처법, 정상 반응과 질환의 구별.", tags: ["역재채기", "호흡기", "정상반응"], animal: "dog", difficulty: "basic", viralScore: 78 },
      { title: "반려동물 엑스레이와 초음파 차이", description: "영상 진단의 두 축인 X-ray와 초음파의 활용 분야와 장단점.", tags: ["X선", "초음파", "진단"], animal: "both", difficulty: "basic", viralScore: 70 },
      { title: "혈액검사 결과 읽는 법", description: "BUN, Creatinine, ALT, ALP 등 주요 혈액 수치의 의미 해석.", tags: ["혈액검사", "수치해석", "진단"], animal: "both", difficulty: "intermediate", viralScore: 82 },
      { title: "반려동물 MRI와 CT 검사", description: "신경과, 종양 진단에 활용되는 고급 영상 검사의 적응증과 비용.", tags: ["MRI", "CT", "영상진단"], animal: "both", difficulty: "advanced", viralScore: 71 },
      { title: "홈 케어 — 약 먹이는 방법", description: "알약, 시럽, 안약, 귀약 등 가정에서 약물 투여하는 실전 팁.", tags: ["약투여", "홈케어", "실전팁"], animal: "both", difficulty: "basic", viralScore: 85 },
      { title: "엘리자베스 칼라 대안 — 편한 보호대 추천", description: "전통 깔때기 칼라의 대안으로 넥 쿠션, 바디수트, 소프트 칼라 비교.", tags: ["칼라", "보호대", "편의용품"], animal: "both", difficulty: "basic", viralScore: 80 },
      { title: "반려동물 재활 물리치료", description: "수중 트레드밀, 레이저 치료, 전기자극 등 재활 치료의 종류와 효과.", tags: ["재활", "물리치료", "수중치료"], animal: "both", difficulty: "intermediate", viralScore: 76 },
      { title: "동물병원 비용 — 진료비 구성 이해하기", description: "진찰료, 검사비, 처치료 등 동물병원 비용 구성과 절약 팁.", tags: ["진료비", "비용", "절약"], animal: "both", difficulty: "basic", viralScore: 88 },
      { title: "세컨드 오피니언의 중요성", description: "큰 수술이나 비용이 많이 드는 치료 전 다른 수의사 의견을 구하는 이유.", tags: ["세컨드오피니언", "수의사", "의사결정"], animal: "both", difficulty: "basic", viralScore: 79 },
      { title: "원격 진료(텔레메디신)의 가능성과 한계", description: "반려동물 원격 진료가 가능한 영역과 대면 진료가 필수인 상황.", tags: ["원격진료", "텔레메디신", "디지털"], animal: "both", difficulty: "basic", viralScore: 74 },
      { title: "반려동물 건강 기록 관리 앱 추천", description: "예방접종, 검사 결과, 투약 이력을 관리하는 유용한 앱 소개.", tags: ["건강기록", "앱", "관리"], animal: "both", difficulty: "basic", viralScore: 77 },
      { title: "수의사와 효과적으로 소통하는 방법", description: "증상 기록, 영상 촬영, 질문 리스트 등 진료 시 소통 향상 팁.", tags: ["소통", "수의사", "진료팁"], animal: "both", difficulty: "basic", viralScore: 76 },
      { title: "동물병원 선택 기준 — 좋은 병원 찾는 법", description: "장비, 전문성, 응급 대응, 소통 능력 등 동물병원 선택 체크리스트.", tags: ["병원선택", "체크리스트", "가이드"], animal: "both", difficulty: "basic", viralScore: 83 },
    ]
  },
];

// ============ 행동분석학 200 topics (8 subcategories x 25) ============
const behaviorSubcategories = [
  {
    id: "beh-psychology", name: "행동심리", icon: "🧠",
    topics: [
      { title: "강아지의 감정 — 기쁨, 공포, 질투도 느낄까?", description: "최신 신경과학 연구로 밝혀진 반려동물의 감정 범위와 표현 방식.", tags: ["감정", "심리", "신경과학"], animal: "both", difficulty: "basic", viralScore: 88 },
      { title: "고전적 조건화 — 파블로프의 개 실험", description: "자극-반응 연합 학습의 원리와 반려동물 훈련에의 적용.", tags: ["조건화", "학습이론", "파블로프"], animal: "both", difficulty: "intermediate", viralScore: 72 },
      { title: "조작적 조건화 — 강화와 벌의 과학", description: "양성 강화, 음성 강화, 양성 벌, 음성 벌의 정확한 의미와 예시.", tags: ["강화", "벌", "조작적조건화"], animal: "both", difficulty: "intermediate", viralScore: 75 },
      { title: "반려동물의 인지 능력 — 문제 해결과 추론", description: "강아지가